// Generated by generate-sleep-profile-registry.py; do not edit.
// Successor-only authority; historical build-info and registry defaults stay v1.
package com.healthmd.core

const val HEALTHMD_SLEEP_REGISTRY_SHA256: String = "709df0ae9f583e82627bc5439c4385905a5d85000e4322a0384cfe96b35a8f78"
