// Generated by generate-sleep-profile-registry.py; do not edit.
// Successor-only authority; historical build-info and registry defaults stay v1.
package com.healthmd.core

const val HEALTHMD_SLEEP_REGISTRY_SHA256: String = "c1854454bee84b6d74cee1d7457d3fde1f484ef74963a656adba503c91cb9073"
