// Generated by packages/contracts/diagnostics/generate.py; do not edit.
package com.healthmd.diagnostics

import java.util.UUID

enum class DiagnosticEventID(val wire: String, val subsystem: String, val severity: String) {
    APP_STARTED("app.started", "lifecycle", "info"),
    NATIVE_LIFECYCLE("app.native_lifecycle", "lifecycle", "info"),
    ADVERTISING_STARTED("sync.advertising_started", "connection", "debug"),
    ADVERTISING_STOPPED("sync.advertising_stopped", "connection", "debug"),
    BROWSING_STARTED("sync.browsing_started", "connection", "debug"),
    BROWSING_STOPPED("sync.browsing_stopped", "connection", "debug"),
    PEER_DISCOVERED("sync.peer_discovered", "connection", "debug"),
    PEER_LOST("sync.peer_lost", "connection", "debug"),
    INVITATION_SENT("sync.invitation_sent", "connection", "debug"),
    INVITATION_RECEIVED("sync.invitation_received", "connection", "debug"),
    INVITATION_TIMEOUT("sync.invitation_timeout", "connection", "warning"),
    CONNECTION_CHANGED("sync.connection_changed", "connection", "info"),
    CAPABILITIES_RECEIVED("sync.capabilities_received", "connection", "debug"),
    DESTINATION_CHANGED("sync.destination_changed", "connection", "debug"),
    MESSAGE_SENT("sync.message_sent", "connection", "trace"),
    MESSAGE_RECEIVED("sync.message_received", "connection", "trace"),
    TRANSPORT_ERROR("sync.transport_error", "connection", "error"),
    EXPORT_RESULT("export.result", "export", "info"),
    REQUEST_QUEUED("schedule.request_queued", "schedule", "info"),
    ATTEMPT_STARTED("schedule.attempt_started", "schedule", "info"),
    ATTEMPT_FINISHED("schedule.attempt_finished", "schedule", "info"),
    BACKGROUND_EXPIRED("schedule.background_expired", "schedule", "warning"),
    TRIGGER_RECEIVED("schedule.trigger_received", "schedule", "debug"),
    WORKER_RESULT("schedule.worker_result", "schedule", "info"),
    NOTIFICATION_REQUESTED("notification.requested", "notification", "info"),
    NOTIFICATION_CANCELLED("notification.cancelled", "notification", "debug"),
    NOTIFICATION_TAPPED("notification.tapped", "notification", "info"),
    NOTIFICATION_FAILED("notification.request_failed", "notification", "error"),
    RECORDING_STARTED("diagnostics.recording_started", "diagnostics", "info"),
    RECORDING_STOPPED("diagnostics.recording_stopped", "diagnostics", "info"),
}

enum class DiagnosticField(val wire: String, val isPrivate: Boolean) {
    NATIVE_CALLBACK("native_callback", false),
    STATE("state", false),
    TRANSPORT("transport", false),
    TRIGGER("trigger", false),
    REASON("reason", false),
    ERROR_DOMAIN("error_domain", false),
    ERROR_CODE("error_code", false),
    DURATION_MS("duration_ms", false),
    BYTE_COUNT("byte_count", false),
    FILE_COUNT("file_count", false),
    DAY_COUNT("day_count", false),
    READY("ready", false),
    PENDING_ONLY("pending_only", false),
    OPERATION_ID("operation_id", false),
    PEER_ALIAS("peer_alias", false),
    PEER_NAME("peer_name", true),
    ;

    fun accepts(value: DiagnosticValue): Boolean = when (this) {
        NATIVE_CALLBACK -> value is DiagnosticValue.Text && value.value in setOf("ios_application_did_become_active", "ios_scene_phase_active", "ios_scene_phase_inactive", "ios_scene_phase_background", "macos_application_did_become_active", "macos_application_did_resign_active", "android_activity_resumed", "android_activity_paused")
        STATE -> value is DiagnosticValue.Text && value.value in setOf("disconnected", "connecting", "connected", "pairing", "transferring", "completed", "failed", "unknown")
        TRANSPORT -> value is DiagnosticValue.Text && value.value in setOf("nearby", "manual_ip")
        TRIGGER -> value is DiagnosticValue.Text && value.value in setOf("app_open", "silent_push", "background_task", "notification", "handshake", "schedule", "manual")
        REASON -> value is DiagnosticValue.Text && value.value in setOf("success", "partial", "failure", "cancelled", "timeout", "suspended", "retry", "unknown")
        ERROR_DOMAIN -> value is DiagnosticValue.Text && value.value in setOf("NSPOSIXErrorDomain", "NSCocoaErrorDomain", "NSURLErrorDomain", "MCErrorDomain", "HKErrorDomain", "IOException", "SecurityException", "unknown")
        ERROR_CODE -> value is DiagnosticValue.Integer && value.value in -9_007_199_254_740_991L..9_007_199_254_740_991L
        DURATION_MS -> value is DiagnosticValue.Integer && value.value in 0..9_007_199_254_740_991L
        BYTE_COUNT -> value is DiagnosticValue.Integer && value.value in 0..9_007_199_254_740_991L
        FILE_COUNT -> value is DiagnosticValue.Integer && value.value in 0..9_007_199_254_740_991L
        DAY_COUNT -> value is DiagnosticValue.Integer && value.value in 0..9_007_199_254_740_991L
        READY -> value is DiagnosticValue.Boolean
        PENDING_ONLY -> value is DiagnosticValue.Boolean
        OPERATION_ID -> value is DiagnosticValue.Text && value.value.length == 36 && runCatching { UUID.fromString(value.value) }.isSuccess
        PEER_ALIAS -> value is DiagnosticValue.Text && Regex("^peer_[0-9]{1,3}$").matches(value.value)
        PEER_NAME -> value is DiagnosticValue.Text && value.value.toByteArray(Charsets.UTF_8).size <= 512
    }
}
