// Independent literal expectations from semantic.rs; never generated by candidate codecs.
// Source map: ExactNumber/validate_number/exact_numbers_reject_nonfinite_and_preserve_negative_zero_bits;
// canonical_signed/unsigned + parse_canonical_i128/u128/u64/i64;
// ExactTimestamp/validate_timestamp/valid_offset; parse_date (Gregorian year 1..9998).
// No scalar version exists: version fields below reject as unknown fields only.
export interface ExactVector {
  readonly id: string;
  readonly codec: "number" | "timestamp" | "ordinal" | "epoch" | "date";
  readonly input: unknown;
  readonly valid: boolean;
  readonly encoded?: string;
}
export const exactVectors: readonly ExactVector[] = [
  {
    "id": "positive-zero",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "0000000000000000"
    },
    "valid": true,
    "encoded": "{\"representation\":\"binary64\",\"bits\":\"0000000000000000\"}"
  },
  {
    "id": "negative-zero",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "8000000000000000"
    },
    "valid": true,
    "encoded": "{\"representation\":\"binary64\",\"bits\":\"8000000000000000\"}"
  },
  {
    "id": "one",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "3ff0000000000000"
    },
    "valid": true,
    "encoded": "{\"representation\":\"binary64\",\"bits\":\"3ff0000000000000\"}"
  },
  {
    "id": "smallest-subnormal",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "0000000000000001"
    },
    "valid": true,
    "encoded": "{\"representation\":\"binary64\",\"bits\":\"0000000000000001\"}"
  },
  {
    "id": "largest-finite",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "7fefffffffffffff"
    },
    "valid": true,
    "encoded": "{\"representation\":\"binary64\",\"bits\":\"7fefffffffffffff\"}"
  },
  {
    "id": "negative-largest-finite",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "ffefffffffffffff"
    },
    "valid": true,
    "encoded": "{\"representation\":\"binary64\",\"bits\":\"ffefffffffffffff\"}"
  },
  {
    "id": "infinity",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "7ff0000000000000"
    },
    "valid": false
  },
  {
    "id": "negative-infinity",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "fff0000000000000"
    },
    "valid": false
  },
  {
    "id": "quiet-nan",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "7ff8000000000000"
    },
    "valid": false
  },
  {
    "id": "signaling-nan",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "7ff0000000000001"
    },
    "valid": false
  },
  {
    "id": "negative-nan",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "fff8000000000000"
    },
    "valid": false
  },
  {
    "id": "uppercase",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "3FF0000000000000"
    },
    "valid": false
  },
  {
    "id": "short",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "0000"
    },
    "valid": false
  },
  {
    "id": "long",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "00000000000000000"
    },
    "valid": false
  },
  {
    "id": "nonhex",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "gg00000000000000"
    },
    "valid": false
  },
  {
    "id": "signed_integer-0",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "0"
    },
    "valid": true,
    "encoded": "{\"representation\":\"signed_integer\",\"decimal\":\"0\"}"
  },
  {
    "id": "signed_integer-1",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "-1"
    },
    "valid": true,
    "encoded": "{\"representation\":\"signed_integer\",\"decimal\":\"-1\"}"
  },
  {
    "id": "signed_integer-2",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "9007199254740993"
    },
    "valid": true,
    "encoded": "{\"representation\":\"signed_integer\",\"decimal\":\"9007199254740993\"}"
  },
  {
    "id": "signed_integer-3",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "-170141183460469231731687303715884105728"
    },
    "valid": true,
    "encoded": "{\"representation\":\"signed_integer\",\"decimal\":\"-170141183460469231731687303715884105728\"}"
  },
  {
    "id": "signed_integer-4",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "170141183460469231731687303715884105727"
    },
    "valid": true,
    "encoded": "{\"representation\":\"signed_integer\",\"decimal\":\"170141183460469231731687303715884105727\"}"
  },
  {
    "id": "unsigned_integer-0",
    "codec": "number",
    "input": {
      "representation": "unsigned_integer",
      "decimal": "0"
    },
    "valid": true,
    "encoded": "{\"representation\":\"unsigned_integer\",\"decimal\":\"0\"}"
  },
  {
    "id": "unsigned_integer-1",
    "codec": "number",
    "input": {
      "representation": "unsigned_integer",
      "decimal": "9007199254740993"
    },
    "valid": true,
    "encoded": "{\"representation\":\"unsigned_integer\",\"decimal\":\"9007199254740993\"}"
  },
  {
    "id": "unsigned_integer-2",
    "codec": "number",
    "input": {
      "representation": "unsigned_integer",
      "decimal": "340282366920938463463374607431768211455"
    },
    "valid": true,
    "encoded": "{\"representation\":\"unsigned_integer\",\"decimal\":\"340282366920938463463374607431768211455\"}"
  },
  {
    "id": "signed-overflow",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "170141183460469231731687303715884105728"
    },
    "valid": false
  },
  {
    "id": "signed-underflow",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "-170141183460469231731687303715884105729"
    },
    "valid": false
  },
  {
    "id": "unsigned-overflow",
    "codec": "number",
    "input": {
      "representation": "unsigned_integer",
      "decimal": "340282366920938463463374607431768211456"
    },
    "valid": false
  },
  {
    "id": "unsigned-negative",
    "codec": "number",
    "input": {
      "representation": "unsigned_integer",
      "decimal": "-1"
    },
    "valid": false
  },
  {
    "id": "noncanonical-0",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "-0"
    },
    "valid": false
  },
  {
    "id": "noncanonical-1",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "+1"
    },
    "valid": false
  },
  {
    "id": "noncanonical-2",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "01"
    },
    "valid": false
  },
  {
    "id": "noncanonical-3",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "-01"
    },
    "valid": false
  },
  {
    "id": "noncanonical-4",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "1e3"
    },
    "valid": false
  },
  {
    "id": "noncanonical-5",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "1.0"
    },
    "valid": false
  },
  {
    "id": "noncanonical-6",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": " 1"
    },
    "valid": false
  },
  {
    "id": "noncanonical-7",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "1 "
    },
    "valid": false
  },
  {
    "id": "noncanonical-8",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": ""
    },
    "valid": false
  },
  {
    "id": "noncanonical-9",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "１"
    },
    "valid": false
  },
  {
    "id": "noncanonical-10",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "١"
    },
    "valid": false
  },
  {
    "id": "noncanonical-11",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "1\n"
    },
    "valid": false
  },
  {
    "id": "number-unknown",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "0000000000000000",
      "extra": 1
    },
    "valid": false
  },
  {
    "id": "number-version",
    "codec": "number",
    "input": {
      "representation": "binary64",
      "bits": "0000000000000000",
      "version": 1
    },
    "valid": false
  },
  {
    "id": "number-wrong-tag",
    "codec": "number",
    "input": {
      "representation": "binary32",
      "bits": "0000000000000000"
    },
    "valid": false
  },
  {
    "id": "number-cross-field",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": "1",
      "bits": "0000000000000000"
    },
    "valid": false
  },
  {
    "id": "number-missing",
    "codec": "number",
    "input": {
      "representation": "signed_integer"
    },
    "valid": false
  },
  {
    "id": "number-rounded",
    "codec": "number",
    "input": {
      "representation": "signed_integer",
      "decimal": 9007199254740992
    },
    "valid": false
  },
  {
    "id": "number-null",
    "codec": "number",
    "input": null,
    "valid": false
  },
  {
    "id": "number-array",
    "codec": "number",
    "input": [],
    "valid": false
  },
  {
    "id": "ordinal-zero",
    "codec": "ordinal",
    "input": "0",
    "valid": true,
    "encoded": "0"
  },
  {
    "id": "ordinal-max",
    "codec": "ordinal",
    "input": "18446744073709551615",
    "valid": true,
    "encoded": "18446744073709551615"
  },
  {
    "id": "ordinal-overflow",
    "codec": "ordinal",
    "input": "18446744073709551616",
    "valid": false
  },
  {
    "id": "ordinal-negative",
    "codec": "ordinal",
    "input": "-1",
    "valid": false
  },
  {
    "id": "epoch-min",
    "codec": "epoch",
    "input": "-9223372036854775808",
    "valid": true,
    "encoded": "-9223372036854775808"
  },
  {
    "id": "epoch-max",
    "codec": "epoch",
    "input": "9223372036854775807",
    "valid": true,
    "encoded": "9223372036854775807"
  },
  {
    "id": "epoch-overflow",
    "codec": "epoch",
    "input": "9223372036854775808",
    "valid": false
  },
  {
    "id": "epoch-underflow",
    "codec": "epoch",
    "input": "-9223372036854775809",
    "valid": false
  },
  {
    "id": "epoch-minuszero",
    "codec": "epoch",
    "input": "-0",
    "valid": false
  },
  {
    "id": "timestamp-min",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "-9223372036854775808",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": -64800
    },
    "valid": true,
    "encoded": "{\"epoch_seconds\":\"-9223372036854775808\",\"nanoseconds\":0,\"source_utc_offset_seconds\":null,\"calendar_utc_offset_seconds\":-64800}"
  },
  {
    "id": "timestamp-max",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "9223372036854775807",
      "nanoseconds": 999999999,
      "source_utc_offset_seconds": 64800,
      "calendar_utc_offset_seconds": 64800
    },
    "valid": true,
    "encoded": "{\"epoch_seconds\":\"9223372036854775807\",\"nanoseconds\":999999999,\"source_utc_offset_seconds\":64800,\"calendar_utc_offset_seconds\":64800}"
  },
  {
    "id": "timestamp-nonhour",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "-1",
      "nanoseconds": 1,
      "source_utc_offset_seconds": 20700,
      "calendar_utc_offset_seconds": -14400
    },
    "valid": true,
    "encoded": "{\"epoch_seconds\":\"-1\",\"nanoseconds\":1,\"source_utc_offset_seconds\":20700,\"calendar_utc_offset_seconds\":-14400}"
  },
  {
    "id": "timestamp-source-min",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": -64800,
      "calendar_utc_offset_seconds": 0
    },
    "valid": true,
    "encoded": "{\"epoch_seconds\":\"0\",\"nanoseconds\":0,\"source_utc_offset_seconds\":-64800,\"calendar_utc_offset_seconds\":0}"
  },
  {
    "id": "timestamp-omitted-source",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "calendar_utc_offset_seconds": 0
    },
    "valid": true,
    "encoded": "{\"epoch_seconds\":\"0\",\"nanoseconds\":0,\"source_utc_offset_seconds\":null,\"calendar_utc_offset_seconds\":0}"
  },
  {
    "id": "nanos-negative",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": -1,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "nanos-over",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 1000000000,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "nanos-fraction",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0.5,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "nanos-string",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": "1",
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "source-over",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": 64801,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "source-under",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": -64801,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "source-fraction",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": 1.5,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "calendar-over",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 64801
    },
    "valid": false
  },
  {
    "id": "calendar-under",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": -64801
    },
    "valid": false
  },
  {
    "id": "calendar-fraction",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0.5
    },
    "valid": false
  },
  {
    "id": "calendar-null",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": null
    },
    "valid": false
  },
  {
    "id": "seconds-number",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": 0,
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "seconds-over",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "9223372036854775808",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "seconds-minuszero",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "-0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0
    },
    "valid": false
  },
  {
    "id": "timestamp-unknown",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0,
      "extra": 1
    },
    "valid": false
  },
  {
    "id": "timestamp-version",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0,
      "source_utc_offset_seconds": null,
      "calendar_utc_offset_seconds": 0,
      "version": 2
    },
    "valid": false
  },
  {
    "id": "calendar-missing",
    "codec": "timestamp",
    "input": {
      "epoch_seconds": "0",
      "nanoseconds": 0
    },
    "valid": false
  },
  {
    "id": "civil-0001-01-01",
    "codec": "date",
    "input": "0001-01-01",
    "valid": true,
    "encoded": "0001-01-01"
  },
  {
    "id": "civil-9998-12-31",
    "codec": "date",
    "input": "9998-12-31",
    "valid": true,
    "encoded": "9998-12-31"
  },
  {
    "id": "civil-2000-02-29",
    "codec": "date",
    "input": "2000-02-29",
    "valid": true,
    "encoded": "2000-02-29"
  },
  {
    "id": "civil-2024-02-29",
    "codec": "date",
    "input": "2024-02-29",
    "valid": true,
    "encoded": "2024-02-29"
  },
  {
    "id": "civil-1900-02-28",
    "codec": "date",
    "input": "1900-02-28",
    "valid": true,
    "encoded": "1900-02-28"
  },
  {
    "id": "civil-2026-04-30",
    "codec": "date",
    "input": "2026-04-30",
    "valid": true,
    "encoded": "2026-04-30"
  },
  {
    "id": "bad-civil-0000-01-01",
    "codec": "date",
    "input": "0000-01-01",
    "valid": false
  },
  {
    "id": "bad-civil-9999-01-01",
    "codec": "date",
    "input": "9999-01-01",
    "valid": false
  },
  {
    "id": "bad-civil-1900-02-29",
    "codec": "date",
    "input": "1900-02-29",
    "valid": false
  },
  {
    "id": "bad-civil-2100-02-29",
    "codec": "date",
    "input": "2100-02-29",
    "valid": false
  },
  {
    "id": "bad-civil-2023-02-29",
    "codec": "date",
    "input": "2023-02-29",
    "valid": false
  },
  {
    "id": "bad-civil-2024-02-30",
    "codec": "date",
    "input": "2024-02-30",
    "valid": false
  },
  {
    "id": "bad-civil-2026-04-31",
    "codec": "date",
    "input": "2026-04-31",
    "valid": false
  },
  {
    "id": "bad-civil-2026-00-01",
    "codec": "date",
    "input": "2026-00-01",
    "valid": false
  },
  {
    "id": "bad-civil-2026-13-01",
    "codec": "date",
    "input": "2026-13-01",
    "valid": false
  },
  {
    "id": "bad-civil-2026-01-00",
    "codec": "date",
    "input": "2026-01-00",
    "valid": false
  },
  {
    "id": "bad-civil-2026-01-32",
    "codec": "date",
    "input": "2026-01-32",
    "valid": false
  },
  {
    "id": "bad-civil-2026-1-01",
    "codec": "date",
    "input": "2026-1-01",
    "valid": false
  },
  {
    "id": "bad-civil-2026-01-1",
    "codec": "date",
    "input": "2026-01-1",
    "valid": false
  },
  {
    "id": "bad-civil-2026-01-01Z",
    "codec": "date",
    "input": "2026-01-01Z",
    "valid": false
  },
  {
    "id": "bad-civil-２０２６-01-01",
    "codec": "date",
    "input": "２０２６-01-01",
    "valid": false
  },
  {
    "id": "bad-civil- 2026-01-01",
    "codec": "date",
    "input": " 2026-01-01",
    "valid": false
  }
];
