//! Issuer-private host authority. Planning can only open existing protected key/grant/root
//! records. Local enrollment/decisions are separate non-Codable native/human interfaces.
use std::{path::PathBuf, sync::Arc};

use async_trait::async_trait;
use base64::{Engine as _, engine::general_purpose::STANDARD};
use fs2::FileExt as _;
use healthmd_protocol::v4::{
    self, Approval, Authority, AuthorityReference, AuthorityReferenceIssuer, Binding,
    ConfigurationContext, ControlUuid, Destination, Digest, Discovery, DiscoveryEntitlement, Error,
    ExportDelegation, ExportDelegationBoundsDestinationPolicy, ExportPlan, Peer, UtcTimestamp,
    ValidateShape, approval_binding, delegation_reference, derived_export_authority, plan_digest,
    validate_export_delegation,
};
use hmac::{Hmac, Mac as _};
use secrecy::{ExposeSecret as _, SecretBox, SecretString};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::fmt::Write as _;

use crate::{
    ClientError,
    agent_private_fs::{self as private, RootIdentity},
    credentials::CredentialStore,
};

const STATE: &str = "issuer.json";
const LOCK: &str = "issuer.lock";
const MAX_BYTES: usize = 1_048_576;
const MAX_GRANTS: usize = 32;
const MAX_PLANS: usize = 128;
const MAC_DOMAIN: &[u8] = b"HealthMd.AgentBridge.HostIssuerStore.v1\0";

/// Read-only protected-key seam. Missing keys must not be regenerated by a planner.
#[async_trait]
pub trait ProtectedHostKey: Send + Sync {
    async fn load_existing(&self, host: &ControlUuid) -> Result<SecretString, ClientError>;
}

/// Production native credential adapter. Provisioning this distinct account is a separate
/// native setup step; this adapter has no write/delete/fallback operation.
pub use crate::agent_host_key::NativeHostKeyReader;
/// Secret return type for externally injected native key readers; not a wire DTO.
pub use secrecy::SecretString as ProtectedHostSecret;
pub struct NativeProtectedHostKey<C = NativeHostKeyReader>(pub C);
#[async_trait]
impl<C: CredentialStore> ProtectedHostKey for NativeProtectedHostKey<C> {
    async fn load_existing(&self, host: &ControlUuid) -> Result<SecretString, ClientError> {
        self.0
            .get(&format!("agent-host-issuer-v1-{}", host.0))
            .await?
            .ok_or(ClientError::AgentAuthorityUnavailable)
    }
}

/// Implement only in a native/human consent surface, never from an MCP/wire field.
/// Implementations must obtain separate explicit local consent for the exact records.
#[async_trait]
pub trait LocalHostConsent: Send + Sync {
    async fn enroll(&self, candidate: &LocalEnrollment) -> Result<(), ClientError>;
    async fn decide(&self, plan: &ExportPlan) -> Result<(), ClientError>;
}

/// Intentionally not serializable: root enrollment is not a portable contract or RPC.
pub struct LocalEnrollment {
    pub delegation: ExportDelegation,
    pub binding_id: ControlUuid,
    pub root: PathBuf,
}

#[derive(Clone)]
pub struct HostAuthorityStore {
    path: PathBuf,
    host: ControlUuid,
    directory_identity: RootIdentity,
    protected_key: Arc<dyn ProtectedHostKey>,
}

#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct GrantRecord {
    description: ExportDelegation,
    reference: AuthorityReference,
    revoked: bool,
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct RootRecord {
    peer: Peer,
    destination: Destination,
    path: PathBuf,
    identity: RootIdentity,
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Decision {
    decision_id: ControlUuid,
    binding: Binding,
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct IssuedPlan {
    plan: ExportPlan,
    discovery: Discovery,
    host_authority: Authority,
    #[serde(skip_serializing_if = "Option::is_none")]
    decision: Option<Decision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    native_approval: Option<Approval>,
}
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct State {
    version: u64,
    host: ControlUuid,
    directory_identity: RootIdentity,
    revision: u64,
    grants: Vec<GrantRecord>,
    roots: Vec<RootRecord>,
    plans: Vec<IssuedPlan>,
}
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct SignedState {
    state: State,
    mac: Digest,
}
impl ValidateShape for SignedState {
    fn validate_shape(&self) -> Result<(), Error> {
        self.mac.validate_shape()
    }
}

/// Snapshot from the issuing store, never constructed by parsing caller JSON.
pub(crate) struct HostAuthorization {
    pub store_revision: u64,
    pub delegation: ExportDelegation,
    pub reference: AuthorityReference,
    pub destination: Destination,
}

impl HostAuthorityStore {
    /// Open only existing state. No directories, lockfiles, keys, grants or roots are created.
    /// # Errors
    /// Missing, unsafe, corrupt, lost-key or substituted state fails closed.
    pub async fn open_existing(
        path: PathBuf,
        host: ControlUuid,
        protected_key: Arc<dyn ProtectedHostKey>,
    ) -> Result<Self, ClientError> {
        host.validate_shape()?;
        let (_, directory_identity) = private::inspect_root(&path)?;
        let store = Self {
            path,
            host,
            directory_identity,
            protected_key,
        };
        store.read().await?;
        Ok(store)
    }

    /// Native/human-only initialization with an already provisioned protected key and private
    /// directory. Existing/corrupt state is never replaced. No source permission is issued.
    /// # Errors
    /// Missing consent/key, wrong issuer or unsafe roots reject before publication.
    pub async fn enroll_local(
        path: PathBuf,
        host: ControlUuid,
        protected_key: Arc<dyn ProtectedHostKey>,
        candidate: LocalEnrollment,
        consent: &dyn LocalHostConsent,
    ) -> Result<Self, ClientError> {
        host.validate_shape()?;
        candidate.delegation.validate_shape()?;
        candidate.binding_id.validate_shape()?;
        consent.enroll(&candidate).await?;
        if candidate.delegation.issuer != AuthorityReferenceIssuer::AuthorizedHost
            || candidate.delegation.peer.host_installation_id != host
        {
            return Err(Error::ApprovalRequired.into());
        }
        let ExportDelegationBoundsDestinationPolicy::RegisteredHostBindings { binding_ids } =
            &candidate.delegation.bounds.destination_policy
        else {
            return Err(Error::ApprovalRequired.into());
        };
        if binding_ids != &[candidate.binding_id.clone()] {
            return Err(Error::ApprovalRequired.into());
        }
        let zones = candidate.delegation.bounds.calendar_timezones.clone();
        validate_export_delegation(
            &candidate.delegation,
            &ConfigurationContext {
                calendar_zones: &zones,
                metrics: &[],
                projection_catalog_sha256: None,
            },
        )?;
        let (dir, directory_identity) = private::inspect_root(&path)?;
        private::private_directory(&dir)?;
        let (_, identity) = private::inspect_root(&candidate.root)?;
        let key = key_bytes(&protected_key.load_existing(&host).await?)?;
        let lock = private::open_private(&dir, LOCK, true, true)?;
        lock.try_lock_exclusive()
            .map_err(|_| ClientError::AgentStoreBusy)?;
        let destination = Destination {
            binding_id: candidate.binding_id,
            host_installation_id: host.clone(),
            identity_sha256: private::identity_digest(&identity)?,
            revision: 1,
        };
        let reference = delegation_reference(&candidate.delegation)?;
        let state = State {
            version: 1,
            host: host.clone(),
            directory_identity: directory_identity.clone(),
            revision: 1,
            roots: vec![RootRecord {
                peer: candidate.delegation.peer.clone(),
                destination,
                path: candidate.root,
                identity,
            }],
            grants: vec![GrantRecord {
                description: candidate.delegation,
                reference,
                revoked: false,
            }],
            plans: vec![],
        };
        private::publish(&dir, STATE, &encode(state, &key)?, true)?;
        Ok(Self {
            path,
            host,
            directory_identity,
            protected_key,
        })
    }

    /// Host-only peer-filtered sanitized catalog. Never obtain host references from discovery.
    /// # Errors
    /// Corrupt/private state or missing native key fails closed.
    pub async fn authority_references(
        &self,
        peer: &Peer,
        now: &UtcTimestamp,
    ) -> Result<Vec<AuthorityReference>, ClientError> {
        let state = self.read().await?;
        if peer.host_installation_id != self.host {
            return Err(Error::BindingChanged.into());
        }
        Ok(state
            .grants
            .iter()
            .filter(|g| {
                !g.revoked && g.description.peer == *peer && g.description.expires_at > *now
            })
            .map(|g| g.reference.clone())
            .collect())
    }

    /// CAS version for the local native consent surface; not a wire revision.
    /// # Errors
    /// Fails closed if issuer state is unavailable.
    pub async fn revision(&self) -> Result<u64, ClientError> {
        Ok(self.read().await?.revision)
    }

    pub(crate) async fn authorization(
        &self,
        peer: &Peer,
        binding: &ControlUuid,
        reference: Option<&AuthorityReference>,
        now: &UtcTimestamp,
    ) -> Result<HostAuthorization, ClientError> {
        let state = self.read().await?;
        let roots: Vec<_> = state
            .roots
            .iter()
            .filter(|r| r.peer == *peer && r.destination.binding_id == *binding)
            .collect();
        if roots.len() != 1 || peer.host_installation_id != self.host {
            return Err(Error::NativeRebindRequired.into());
        }
        let root = roots[0];
        if private::inspect_root(&root.path)?.1 != root.identity
            || private::identity_digest(&root.identity)? != root.destination.identity_sha256
        {
            return Err(Error::BindingChanged.into());
        }
        let grants: Vec<_> = state.grants.iter().filter(|g| !g.revoked && g.description.peer == *peer && g.description.expires_at > *now
            && reference.is_none_or(|reference| *reference == g.reference)
            && matches!(&g.description.bounds.destination_policy, ExportDelegationBoundsDestinationPolicy::RegisteredHostBindings { binding_ids } if binding_ids.contains(binding))).collect();
        if grants.len() != 1 {
            return Err(Error::ApprovalRequired.into());
        }
        let grant = grants[0];
        Ok(HostAuthorization {
            store_revision: state.revision,
            delegation: grant.description.clone(),
            reference: grant.reference.clone(),
            destination: root.destination.clone(),
        })
    }

    pub(crate) async fn persist_plan(
        &self,
        expected: u64,
        plan: ExportPlan,
        discovery: Discovery,
        host_authority: Authority,
    ) -> Result<(), ClientError> {
        self.mutate(expected, |state| {
            if state.plans.len() >= MAX_PLANS {
                return Err(ClientError::AgentStoreFull);
            }
            if state.plans.iter().any(|p| {
                p.plan.plan_id == plan.plan_id || p.plan.intent.intent_id == plan.intent.intent_id
            }) {
                return Err(Error::RevisionConflict.into());
            }
            state.plans.push(IssuedPlan {
                plan,
                discovery,
                host_authority,
                decision: None,
                native_approval: None,
            });
            Ok(())
        })
        .await
    }

    pub(crate) async fn issued_plan(
        &self,
        plan_id: &ControlUuid,
    ) -> Result<
        (
            u64,
            ExportPlan,
            Discovery,
            Option<Binding>,
            Option<Approval>,
        ),
        ClientError,
    > {
        let state = self.read().await?;
        let issued = state
            .plans
            .iter()
            .find(|p| p.plan.plan_id == *plan_id)
            .ok_or(Error::ApprovalRequired)?;
        Ok((
            state.revision,
            issued.plan.clone(),
            issued.discovery.clone(),
            issued.decision.as_ref().map(|d| d.binding.clone()),
            issued.native_approval.clone(),
        ))
    }

    /// Separate local exact host decision. An approval relay request cannot call this API.
    /// # Errors
    /// Unissued/changed/expired plans, absent consent or CAS conflicts reject.
    pub async fn record_local_decision(
        &self,
        expected_revision: u64,
        plan_id: &ControlUuid,
        now: &UtcTimestamp,
        consent: &dyn LocalHostConsent,
    ) -> Result<ControlUuid, ClientError> {
        let (_, plan, _, _, _) = self.issued_plan(plan_id).await?;
        self.authorization(
            &plan.intent.peer,
            &plan.intent.destination.binding_id,
            Some(&plan.authority_references.host),
            now,
        )
        .await?;
        if plan.expires_at <= *now {
            return Err(Error::PlanExpired.into());
        }
        consent.decide(&plan).await?;
        let decision_id = ControlUuid(uuid::Uuid::new_v4().to_string());
        self.mutate(expected_revision, |state| {
            let issued = state
                .plans
                .iter_mut()
                .find(|p| p.plan == plan)
                .ok_or(Error::BindingChanged)?;
            if issued.decision.is_some() {
                return Err(Error::RevisionConflict.into());
            }
            issued.decision = Some(Decision {
                decision_id: decision_id.clone(),
                binding: approval_binding(&plan),
            });
            Ok(())
        })
        .await?;
        Ok(decision_id)
    }

    /// Local revocation preserves the tombstone and invalidates all pending plans/decisions.
    /// # Errors
    /// Unknown authority or CAS conflict rejects; no last-writer-wins.
    pub async fn revoke_local(
        &self,
        expected_revision: u64,
        authority: &ControlUuid,
    ) -> Result<(), ClientError> {
        self.mutate(expected_revision, |state| {
            let grant = state
                .grants
                .iter_mut()
                .find(|g| g.reference.authority_id == *authority)
                .ok_or(Error::ApprovalRequired)?;
            grant.revoked = true;
            Ok(())
        })
        .await
    }

    pub(crate) async fn persist_approval(
        &self,
        expected: u64,
        plan: &ExportPlan,
        approval: Approval,
    ) -> Result<(), ClientError> {
        self.mutate(expected, |state| {
            let issued = state
                .plans
                .iter_mut()
                .find(|p| p.plan == *plan)
                .ok_or(Error::BindingChanged)?;
            if issued
                .decision
                .as_ref()
                .is_none_or(|d| d.binding != approval.binding)
            {
                return Err(Error::ApprovalRequired.into());
            }
            if issued
                .native_approval
                .as_ref()
                .is_some_and(|previous| *previous != approval)
            {
                return Err(Error::BindingChanged.into());
            }
            issued.native_approval = Some(approval);
            Ok(())
        })
        .await
    }

    async fn read(&self) -> Result<State, ClientError> {
        let key = key_bytes(&self.protected_key.load_existing(&self.host).await?)?;
        let dir = self.directory()?;
        let lock = private::open_private(&dir, LOCK, false, false)?;
        fs2::FileExt::try_lock_shared(&lock).map_err(|_| ClientError::AgentStoreBusy)?;
        self.read_locked(&dir, &key)
    }

    fn directory(&self) -> Result<cap_std::fs::Dir, ClientError> {
        let (dir, identity) = private::inspect_root(&self.path)?;
        private::private_directory(&dir)?;
        if identity != self.directory_identity {
            return Err(ClientError::AgentAuthorityUnavailable);
        }
        Ok(dir)
    }

    fn read_locked(
        &self,
        dir: &cap_std::fs::Dir,
        key: &SecretBox<[u8; 32]>,
    ) -> Result<State, ClientError> {
        let bytes = private::read_private(dir, STATE, MAX_BYTES)?;
        let signed: SignedState = v4::decode_typed(&bytes).map_err(private::unavailable)?;
        signed.mac.validate_shape().map_err(private::unavailable)?;
        let state = signed.state;
        let expected_mac = mac(&state, key)?;
        if !healthmd_protocol::crypto::constant_time_equal(
            expected_mac.0.as_bytes(),
            signed.mac.0.as_bytes(),
        ) || state.version != 1
            || state.host != self.host
            || state.directory_identity != self.directory_identity
            || state.revision == 0
            || state.grants.len() > MAX_GRANTS
            || state.roots.len() > MAX_GRANTS
            || state.plans.len() > MAX_PLANS
        {
            return Err(ClientError::AgentAuthorityUnavailable);
        }
        validate_state(&state)?;
        Ok(state)
    }

    async fn mutate(
        &self,
        expected: u64,
        change: impl FnOnce(&mut State) -> Result<(), ClientError>,
    ) -> Result<(), ClientError> {
        let key = key_bytes(&self.protected_key.load_existing(&self.host).await?)?;
        let dir = self.directory()?;
        let lock = private::open_private(&dir, LOCK, true, false)?;
        lock.try_lock_exclusive()
            .map_err(|_| ClientError::AgentStoreBusy)?;
        let mut state = self.read_locked(&dir, &key)?;
        if state.revision != expected {
            return Err(Error::RevisionConflict.into());
        }
        change(&mut state)?;
        state.revision = state
            .revision
            .checked_add(1)
            .ok_or(ClientError::AgentStoreFull)?;
        validate_state(&state)?;
        let bytes = encode(state, &key)?;
        if bytes.len() > MAX_BYTES {
            return Err(ClientError::AgentStoreFull);
        }
        private::publish(&dir, STATE, &bytes, false)
    }
}

fn key_bytes(secret: &SecretString) -> Result<SecretBox<[u8; 32]>, ClientError> {
    let bytes = STANDARD
        .decode(secret.expose_secret())
        .map_err(private::unavailable)?;
    let key: [u8; 32] = bytes.try_into().map_err(private::unavailable)?;
    if STANDARD.encode(key) != secret.expose_secret() {
        return Err(ClientError::AgentAuthorityUnavailable);
    }
    Ok(SecretBox::new(Box::new(key)))
}
fn mac(state: &State, key: &SecretBox<[u8; 32]>) -> Result<Digest, ClientError> {
    let mut mac =
        Hmac::<Sha256>::new_from_slice(key.expose_secret()).map_err(private::unavailable)?;
    mac.update(MAC_DOMAIN);
    mac.update(&v4::canonical_json(state)?);
    let mut encoded = String::with_capacity(64);
    for byte in mac.finalize().into_bytes() {
        write!(&mut encoded, "{byte:02x}").map_err(private::unavailable)?;
    }
    Ok(Digest(encoded))
}
fn encode(state: State, key: &SecretBox<[u8; 32]>) -> Result<Vec<u8>, ClientError> {
    let mac = mac(&state, key)?;
    v4::canonical_json(&SignedState { state, mac }).map_err(Into::into)
}
fn validate_state(state: &State) -> Result<(), ClientError> {
    let mut grants = std::collections::BTreeSet::new();
    let mut roots = std::collections::BTreeSet::new();
    let mut plans = std::collections::BTreeSet::new();
    for g in &state.grants {
        g.description
            .validate_shape()
            .map_err(private::unavailable)?;
        if g.description.issuer != AuthorityReferenceIssuer::AuthorizedHost
            || g.description.peer.host_installation_id != state.host
            || delegation_reference(&g.description)? != g.reference
            || !grants.insert(g.reference.authority_id.clone())
        {
            return Err(ClientError::AgentAuthorityUnavailable);
        }
    }
    for r in &state.roots {
        r.destination
            .validate_shape()
            .map_err(private::unavailable)?;
        if r.peer.host_installation_id != state.host
            || r.destination.host_installation_id != state.host
            || private::identity_digest(&r.identity)? != r.destination.identity_sha256
            || !r.path.is_absolute()
            || !roots.insert(r.destination.binding_id.clone())
        {
            return Err(ClientError::AgentAuthorityUnavailable);
        }
    }
    for p in &state.plans {
        p.plan.validate_shape().map_err(private::unavailable)?;
        p.discovery.validate_shape().map_err(private::unavailable)?;
        let parent = state
            .grants
            .iter()
            .find(|g| g.reference == p.plan.authority_references.host)
            .ok_or(ClientError::AgentAuthorityUnavailable)?;
        let derived = derived_export_authority(
            &parent.description,
            &p.plan,
            DiscoveryEntitlement::Satisfied,
            DiscoveryEntitlement::Satisfied,
        )?;
        if p.host_authority != derived {
            return Err(ClientError::AgentAuthorityUnavailable);
        }
        if p.plan.intent.peer.host_installation_id != state.host
            || plan_digest(&p.plan)? != p.plan.plan_sha256
            || !plans.insert(p.plan.plan_id.clone())
            || p.decision
                .as_ref()
                .is_some_and(|d| d.binding != approval_binding(&p.plan))
            || p.native_approval
                .as_ref()
                .is_some_and(|a| a.binding != approval_binding(&p.plan))
        {
            return Err(ClientError::AgentAuthorityUnavailable);
        }
    }
    Ok(())
}
