/** Literal expectations from accepted common source/fixtures; never generated by the candidate imports. */
export const candidateExportVectors = [
  { subpath: "@healthmd/core-ts/candidate/catalog", stem: "operations/catalog", symbols: ["catalogFailure", "catalogMirrorSha256", "createStaticCatalog", "fullOperationIds", "readOnlyOperationIds"], types: ["CatalogTool", "StaticCatalog", "SurfaceProfile", "CatalogResult"] },
  { subpath: "@healthmd/core-ts/candidate/normalize", stem: "operations/normalize", symbols: ["normalizeDiscovery", "normalizeMetricChart"], types: ["QueryInvocation"] },
  { subpath: "@healthmd/core-ts/candidate/query", stem: "operations/query", symbols: ["QuerySource", "ownQueryResource", "traversalBounds", "traverseQuery"], types: ["AttributedPage", "QueryBinding", "QueryFailure", "QueryResource", "QueryScope", "TraversalRequest", "TraversalReceipt"] },
  { subpath: "@healthmd/core-ts/candidate/registry", stem: "contracts/registry", symbols: ["readReviewedRegistry", "registryExpectedSha256"], types: ["RegistryReader", "RegistrySnapshot", "RegistryResult"] },
] as const;
export const excludedSubpaths = [
  "@healthmd/core-ts/package.json", "@healthmd/core-ts/src/operations/query.ts",
  "@healthmd/core-ts/dist/core/operations/query.js", "@healthmd/core-ts/operations/query",
  "@healthmd/core-ts/candidate/exact-values", "@healthmd/core-ts/candidate/internal",
] as const;
export const expectedBounds = { aggregateBytes: 2097152, receiptReserveBytes: 16384, pages: 4096, pageBytes: 1048576, pageItems: 1000 } as const;
export const expectedAuthority = {
  catalog: "31377cf8ac0494d8410a2bd9cf69be0c65d1f0394517730e960f0f9a9016f52d",
  registry: "56def644baa3d81e0c6c2eda3733bfdd7ceee6554ca9ec609da80356c6578c99",
  fullCatalogCount: 21, readOnlyCatalogCount: 13, querySourceKey: "healthmd.candidate.QuerySource",
} as const;
export const normalizationVector = {
  input: { dates: { type: "range", start: "2026-01-01", end: "2026-01-02" }, metrics: ["steps"], all_pages: true },
  expected: {
    query: { schema: "healthmd.query_request", schema_version: 1,
      dates: { type: "range", start: "2026-01-01", end: "2026-01-02" }, metrics: ["steps"],
      sources: { type: "all_available" }, operation: { type: "metric_series" },
      page: { max_items: 250, max_bytes: 262144, cursor: null } },
    detail_level: "summary", all_pages: true,
  },
  rejected: { dates: null, metrics: [], request_id: "not_a_normalizer_argument" },
  failure: { code: "healthmd_invalid_arguments" },
} as const;
export const traversalVector = {
  binding: { caller: "synthetic-cli", source: "synthetic-source", profile: "local_read_only", coverage: "synthetic-partial", logicalQuery: "synthetic-query", dataset: "synthetic-dataset" },
  body: { items: [], next_cursor: null, coverage: "partial" }, encodedBytes: 64,
  expected: { schema: "healthmd.mcp_query_pages", schema_version: 1,
    pages: [{ items: [], next_cursor: null, coverage: "partial" }],
    receipt: { page_count: 1, item_count: 0, packet_fact_count: 0, traversal_complete: true, next_cursor: null, limit_reason: null } },
  resourceCounts: { opened: 1, read: 1, released: 1 },
} as const;
