#!/usr/bin/env python3
"""Generate or verify the deterministic, PHI-free Practice ingest-test PDF."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys

DIRECTORY = Path(__file__).resolve().parent
OUTPUT = DIRECTORY / "synthetic-ingest-test-v1.pdf"
README = DIRECTORY / "README.md"
DISCOVERY_GUIDE = DIRECTORY.parent / "pilot-practice-discovery-and-approval.md"
EXPECTED_SHA256 = "53b5033914f2a451e094bc6432f5bebbfeb75aca51d914f2a6e2afb87ff5aebc"


def pdf_text(value: str) -> bytes:
    """Escape an ASCII string for one PDF literal string."""
    return (
        value.replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
        .encode("ascii")
    )


def build_content_stream() -> bytes:
    lines = [
        (20, 720, "Health.md Practice"),
        (16, 680, "FICTIONAL INGEST TEST"),
        (13, 640, "NO PATIENT OR HEALTH DATA"),
        (11, 595, "Document ID: practice-ingest-test-v1"),
        (11, 565, "Purpose: verify PDF upload, retrieval, viewing, and EHR attachment."),
        (11, 535, "Expected: authorized staff can retrieve and read this exact test page."),
        (11, 490, "Do not replace this file with a real patient document."),
    ]
    commands = [b"BT"]
    for size, x, text in lines:
        commands.extend(
            [
                f"/F1 {size} Tf".encode("ascii"),
                f"1 0 0 1 72 {x} Tm".encode("ascii"),
                b"(" + pdf_text(text) + b") Tj",
            ]
        )
    commands.append(b"ET")
    return b"\n".join(commands) + b"\n"


def build_pdf() -> bytes:
    """Build a minimal deterministic one-page PDF 1.4 document."""
    stream = build_content_stream()
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>"
        ),
        b"<< /Length "
        + str(len(stream)).encode("ascii")
        + b" >>\nstream\n"
        + stream
        + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    output = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, body in enumerate(objects, start=1):
        offsets.append(len(output))
        output.extend(f"{number} 0 obj\n".encode("ascii"))
        output.extend(body)
        output.extend(b"\nendobj\n")

    xref_offset = len(output)
    output.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.extend(
        (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_offset}\n%%EOF\n"
        ).encode("ascii")
    )
    return bytes(output)


def validate_structure(data: bytes) -> None:
    """Validate the exact structural invariants this generator owns."""
    if not data.startswith(b"%PDF-1.4\n") or not data.endswith(b"%%EOF\n"):
        raise ValueError("generated bytes are not a complete PDF 1.4 file")
    if data.count(b" obj\n") != 5 or data.count(b"\nendobj\n") != 5:
        raise ValueError("generated PDF object count is invalid")
    if b"NO PATIENT OR HEALTH DATA" not in data:
        raise ValueError("generated PDF is missing its safety label")

    stream_header = re.search(rb"<< /Length ([0-9]+) >>\nstream\n", data)
    if stream_header is None:
        raise ValueError("generated PDF stream length is missing")
    stream_start = stream_header.end()
    stream_end = data.find(b"endstream", stream_start)
    if stream_end < 0:
        raise ValueError("generated PDF stream terminator is missing")
    declared_length = int(stream_header.group(1))
    if stream_end - stream_start != declared_length:
        raise ValueError("generated PDF stream length is incorrect")

    startxref = re.search(rb"startxref\n([0-9]+)\n%%EOF\n$", data)
    if startxref is None:
        raise ValueError("generated PDF startxref is missing")
    xref_offset = int(startxref.group(1))
    if data[xref_offset : xref_offset + 5] != b"xref\n":
        raise ValueError("generated PDF startxref does not point to xref")

    xref_section = data[xref_offset:].split(b"trailer\n", maxsplit=1)[0].splitlines()
    if len(xref_section) != 8 or xref_section[:3] != [
        b"xref",
        b"0 6",
        b"0000000000 65535 f ",
    ]:
        raise ValueError("generated PDF cross-reference table is invalid")
    for object_number, entry in enumerate(xref_section[3:], start=1):
        if not re.fullmatch(rb"[0-9]{10} 00000 n ", entry):
            raise ValueError("generated PDF cross-reference entry is invalid")
        object_offset = int(entry[:10])
        expected_header = f"{object_number} 0 obj\n".encode("ascii")
        if data[object_offset : object_offset + len(expected_header)] != expected_header:
            raise ValueError("generated PDF cross-reference offset is incorrect")

    if b"/Size 6 /Root 1 0 R" not in data[xref_offset:]:
        raise ValueError("generated PDF trailer metadata is invalid")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed PDF instead of replacing it",
    )
    args = parser.parse_args()

    expected = build_pdf()
    validate_structure(expected)
    digest = hashlib.sha256(expected).hexdigest()
    if EXPECTED_SHA256 == "TO_BE_FILLED":
        print(f"generated sha256={digest}", file=sys.stderr)
        if args.check:
            return 1
    elif digest != EXPECTED_SHA256:
        print(
            f"generator digest mismatch: expected {EXPECTED_SHA256}, built {digest}",
            file=sys.stderr,
        )
        return 1

    if args.check:
        try:
            committed = OUTPUT.read_bytes()
        except FileNotFoundError:
            print(f"missing generated fixture: {OUTPUT}", file=sys.stderr)
            return 1
        try:
            validate_structure(committed)
        except ValueError as error:
            print(f"invalid committed fixture: {error}", file=sys.stderr)
            return 1
        if committed != expected:
            print("committed PDF differs from deterministic generator output", file=sys.stderr)
            return 1
        documentation = {
            README: [
                f"**Byte count:** `{len(expected)}`",
                f"**SHA-256:** `{digest}`",
            ],
            DISCOVERY_GUIDE: [
                "Fixture ID: practice-ingest-test-v1",
                f"Fixture SHA-256: {digest}",
            ],
        }
        for path, required_values in documentation.items():
            try:
                text = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                print(f"missing fixture documentation: {path}", file=sys.stderr)
                return 1
            for required in required_values:
                if required not in text:
                    print(
                        f"fixture documentation is stale in {path}: missing {required!r}",
                        file=sys.stderr,
                    )
                    return 1
        print(f"synthetic ingest PDF and documentation verified: {digest}")
        return 0

    OUTPUT.write_bytes(expected)
    print(f"wrote {OUTPUT} ({len(expected)} bytes, sha256={digest})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
