import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const WEBSITE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(WEBSITE, 'docs-src');
const APPLE_REFERENCE = path.resolve(WEBSITE, '../apple/docs/reference');
const lock = JSON.parse(await readFile(path.join(DOCS, 'reference-source.json'), 'utf8'));

test('every synchronized reference page names its generator and owning source', async () => {
  for (const output of lock.published_outputs.filter((entry) => entry.classification === 'rendered-page')) {
    const markdown = await readFile(path.join(DOCS, output.path), 'utf8');
    assert.match(markdown, /<!-- Generated by apps\/website\/docs-src\/scripts\/sync-export-reference\.mjs\./, output.path);
    assert.match(markdown, /Regenerate from apps\/website: npm run reference:sync/, output.path);
    const source = lock.files.find((entry) => entry.routes.rendered === output.route);
    const expected = source
      ? `Source: apps/apple/docs/reference/${source.path}`
      : 'Source: apps/apple/docs/reference/ (artifact inventory)';
    assert.ok(markdown.includes(expected), `${output.path} should name ${expected}`);
    assert.ok(markdown.indexOf('<!-- Generated') < markdown.indexOf('-->'), output.path);
  }
});

test('reference provenance banners do not change any raw fixture bytes', async () => {
  for (const source of lock.files.filter((entry) => entry.routes.raw)) {
    const relative = source.path.slice('generated/'.length);
    const [canonical, publication] = await Promise.all([
      readFile(path.join(APPLE_REFERENCE, source.path)),
      readFile(path.join(DOCS, 'public/reference/generated', relative)),
    ]);
    assert.deepEqual(publication, canonical, source.path);
  }
});
