#!/usr/bin/env python3
"""Derive successor-only registry v2 without repinning the shipped registry v1."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "crates/healthmd-core/registry"
LEGACY = DIRECTORY / "metric-registry-v1.json"
SUCCESSOR = DIRECTORY / "metric-registry-v2.json"
LEGACY_SHA256 = "56def644baa3d81e0c6c2eda3733bfdd7ceee6554ca9ec609da80356c6578c99"
KOTLIN_AUTHORITY = (
    ROOT.parents[1] / "apps/android/healthmd-core/src/main/kotlin/com/healthmd/core/SleepProfileContract.kt"
)
SWIFT_AUTHORITY = (
    ROOT.parents[1] / "apps/apple/Packages/HealthMdCoreRust/Sources/HealthMdCoreRust/Generated/SleepProfileContract.swift"
)


def successor_document() -> dict:
    original = LEGACY.read_bytes()
    if hashlib.sha256(original).hexdigest() != LEGACY_SHA256:
        raise SystemExit("Historical registry v1 changed; refusing to derive successor profiles")
    document = json.loads(original)
    old_profiles = {p["id"]: p for p in document["profiles"]}
    apple = copy.deepcopy(old_profiles["apple_health_data_v8"])
    apple.update(id="apple_health_data_v11", public_profile_id="apple-v11", public_schema_version=11)
    android = copy.deepcopy(old_profiles["android_analytical_v5"])
    android.update(id="android_sleep_v6", public_profile_id="android-sleep-v6", public_schema_version=6)

    # Preserve source selection identities and ordinals while refusing the historical
    # Core/Light alias in a newly defined profile. Related is not equivalent.
    core = next(m for m in document["metrics"] if m["semantic_id"] == "sleep_core")
    light_binding = copy.deepcopy(core["android"])
    core["equivalence"] = "platform_distinct"
    core["apple"]["related_semantic_ids"] = ["sleep_light"]
    core["android"] = {
        "status": "unavailable",
        "reason_key": "health_connect_no_exact_core_sleep",
        "picker_visibility": "hidden",
    }
    light_binding["related_semantic_ids"] = ["sleep_core"]
    document["metrics"].append({
        "semantic_id": "sleep_light",
        "reference_name": "Light Sleep",
        "capability_id": "export.sleep-summary",
        "equivalence": "platform_distinct",
        "apple": {
            "status": "unavailable",
            "reason_key": "healthkit_no_exact_light_sleep",
            "picker_visibility": "hidden",
        },
        "android": light_binding,
    })

    outputs = []
    for output in android["outputs"]:
        if output["key"] == "sleep_light_hours":
            continue  # Replace the old opt-in duplicate with the real native projection below.
        if output["key"] == "sleep_core_hours":
            output.update(
                key="sleep_light_hours", alias_kind="none", condition="default",
                enabled_by_default=True, platform_native=True, unit="hours",
            )
        outputs.append(output)
    android["outputs"] = outputs
    document["profiles"] = [apple, android]
    document["registry_version"] = 2
    return document


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify without writing")
    args = parser.parse_args()
    data = (json.dumps(successor_document(), indent=2, sort_keys=True, ensure_ascii=False) + "\n").encode()
    digest = hashlib.sha256(data).hexdigest()
    kotlin = (
        "// Generated by generate-sleep-profile-registry.py; do not edit.\n"
        "// Successor-only authority; historical build-info and registry defaults stay v1.\n"
        "package com.healthmd.core\n\n"
        f'const val HEALTHMD_SLEEP_REGISTRY_SHA256: String = "{digest}"\n'
    ).encode()
    swift = (
        "// Generated by generate-sleep-profile-registry.py; do not edit.\n"
        "// Successor-only authority; historical build-info and registry defaults stay v1.\n"
        "public enum HealthMdSleepProfileContract {\n"
        "    public static let registryVersion: UInt32 = 2\n"
        f'    public static let registrySHA256 = "{digest}"\n'
        "}\n"
    ).encode()
    for path, expected in ((SUCCESSOR, data), (KOTLIN_AUTHORITY, kotlin), (SWIFT_AUTHORITY, swift)):
        if args.check:
            if not path.exists() or path.read_bytes() != expected:
                raise SystemExit("Successor registry authority is stale; run generate-sleep-profile-registry.py")
        else:
            path.write_bytes(expected)
    print(f"registry v2 SHA-256: {digest}")
    print(f"historical registry v1 SHA-256: {LEGACY_SHA256} (unchanged)")


if __name__ == "__main__":
    main()
