#!/usr/bin/env python3
"""Generate native catalog adapters and public references from the Rust registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[1]
REPO = WORKSPACE.parents[1]
REGISTRY = WORKSPACE / "crates/healthmd-core/registry/metric-registry-v1.json"
APPLE = REPO / "apps/apple/HealthMd/Shared/Models/HealthMetrics.swift"
APPLE_MAPPING = REPO / "apps/apple/HealthMd/Shared/Export/HealthMetricsDictionary.swift"
ANDROID = REPO / "apps/android/app/src/main/java/com/healthmd/domain/model/MetricSelection.kt"
ANDROID_FIELDS = REPO / "apps/android/app/src/main/java/com/healthmd/domain/model/HealthDataFields.kt"
LEDGER = REPO / "apps/android/docs/export-contract/android-ios-metric-parity-ledger.md"
WEBSITE_PAGE = REPO / "apps/website/docs-src/src/content/docs/shared-metric-registry.md"
WEBSITE_JSON = REPO / "apps/website/docs-src/public/reference/metric-registry-v1.json"

APPLE_START = "// BEGIN GENERATED SHARED RUST METRIC REGISTRY"
APPLE_END = "// END GENERATED SHARED RUST METRIC REGISTRY"
APPLE_MAPPING_START = "    // BEGIN GENERATED SHARED RUST EXPORT MAPPING"
APPLE_MAPPING_END = "    // END GENERATED SHARED RUST EXPORT MAPPING"
ANDROID_START = "// BEGIN GENERATED SHARED RUST SELECTABLE METRICS"
ANDROID_END = "// END GENERATED SHARED RUST SELECTABLE METRICS"
FIELDS_START = "    // BEGIN GENERATED SHARED RUST OUTPUT FIELDS"
FIELDS_END = "    // END GENERATED SHARED RUST OUTPUT FIELDS"

CATEGORY_CASE = {
    "Sleep": "sleep", "Activity": "activity", "Heart": "heart", "Respiratory": "respiratory",
    "Vitals": "vitals", "Body Measurements": "bodyMeasurements", "Mobility": "mobility",
    "Cycling": "cycling", "Nutrition": "nutrition", "Vitamins": "vitamins", "Minerals": "minerals",
    "Hearing": "hearing", "Mindfulness": "mindfulness", "Reproductive Health": "reproductiveHealth",
    "Symptoms": "symptoms", "Clinical Records": "clinicalRecords", "Clinical Documents": "clinicalDocuments",
    "Vision": "vision", "Medications": "medications", "Other": "other", "Workouts": "workouts",
}


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def replace_region(text: str, start: str, end: str, replacement: str, fallback_start: str, fallback_end: str) -> str:
    if start in text:
        before, tail = text.split(start, 1)
        _, after = tail.split(end, 1)
        return before + replacement + after
    start_index = text.index(fallback_start)
    end_index = text.index(fallback_end, start_index)
    return text[:start_index] + replacement + "\n\n" + text[end_index:]


def apple_region(document: dict) -> str:
    apple_metrics = [metric for metric in document["metrics"] if metric["apple"]["status"] == "backed"]
    apple_metrics.sort(key=lambda metric: metric["apple"]["ordinal"])
    lines = [
        APPLE_START,
        "// Generated by packages/healthmd-core-rust/scripts/generate-registry-adapters.py.",
        "// Do not edit metric rows here; edit metric-registry-v1.json and regenerate.",
        "struct HealthMetrics {",
        f"    static let registrySHA256 = {quoted(document_registry_sha256(document))}",
        "    static let all: [HealthMetricDefinition] = [",
    ]
    for semantic in apple_metrics:
        metric = semantic["apple"]
        selector = "nil" if metric["source_selector"] == "None" else quoted(metric["source_selector"])
        lines.append(
            "        HealthMetricDefinition("
            f"id: {quoted(metric['selection_id'])}, name: {quoted(metric['reference_name'])}, "
            f"category: .{CATEGORY_CASE[metric['category_id']]}, unit: {quoted(metric['unit'])}, "
            f"healthKitIdentifier: {selector}, metricType: .{metric['kind']}, "
            f"aggregation: .{metric['source_aggregation']}, isArchiveOnly: {str(metric['archive_only']).lower()}, "
            f"isEnabledByDefault: {str(metric['default_enabled']).lower()}, availability: .{metric['availability_key']}),"
        )
    lines += [
        "    ]",
        "",
        "    static var byCategory: [HealthMetricCategory: [HealthMetricDefinition]] {",
        "        Dictionary(grouping: all, by: { $0.category })",
        "    }",
        "",
    ]
    array_properties = [
        ("sleep", "Sleep"), ("activity", "Activity"), ("heart", "Heart"),
        ("respiratory", "Respiratory"), ("vitals", "Vitals"),
        ("bodyMeasurements", "Body Measurements"), ("mobility", "Mobility"),
        ("cycling", "Cycling"), ("nutrition", "Nutrition"), ("vitamins", "Vitamins"),
        ("minerals", "Minerals"), ("hearing", "Hearing"), ("mindfulness", "Mindfulness"),
        ("reproductiveHealth", "Reproductive Health"), ("symptoms", "Symptoms"),
        ("clinicalRecords", "Clinical Records"), ("clinicalDocuments", "Clinical Documents"),
        ("vision", "Vision"), ("medications", "Medications"), ("other", "Other"),
    ]
    for property_name, category in array_properties:
        lines.append(
            f"    static let {property_name} = all.filter {{ $0.category == .{CATEGORY_CASE[category]} }}"
        )
    lines += [
        "    static let workouts = requiredMetric(\"workouts\")",
        "    static let scheduledWorkoutPlans = requiredMetric(\"scheduled_workout_plans\")",
        "",
        "    private static func requiredMetric(_ id: String) -> HealthMetricDefinition {",
        "        guard let metric = all.first(where: { $0.id == id }) else {",
        "            preconditionFailure(\"Generated shared-core metric is missing\")",
        "        }",
        "        return metric",
        "    }",
        "}",
        APPLE_END,
    ]
    return "\n".join(lines)


def apple_mapping_region(document: dict) -> str:
    profile = next(profile for profile in document["profiles"] if profile["id"] == "apple_health_data_v8")
    apple_metrics = [metric["apple"] for metric in document["metrics"] if metric["apple"]["status"] == "backed"]
    apple_metrics.sort(key=lambda metric: metric["ordinal"])
    outputs_by_metric: dict[str, list[str]] = {}
    for output in profile["outputs"]:
        outputs_by_metric.setdefault(output["selection_id"], []).append(output["key"])
    archive_ids = [metric["selection_id"] for metric in apple_metrics if metric["archive_only"]]
    lines = [
        APPLE_MAPPING_START,
        "    // Generated from metric-registry-v1.json. Public keys and order remain unchanged.",
        "    static let reviewedArchiveOnlyMetricIDs: Set<String> = [",
        *[f"        {quoted(metric_id)}," for metric_id in archive_ids],
        "    ]",
        "",
        "    static let metricIdToFrontmatterKeys: [String: [String]] = [",
    ]
    for metric in apple_metrics:
        metric_id = metric["selection_id"]
        keys = outputs_by_metric.get(metric_id)
        if keys:
            lines.append(
                f"        {quoted(metric_id)}: [{', '.join(quoted(key) for key in keys)}],"
            )
    lines += ["    ]", APPLE_MAPPING_END]
    return "\n".join(lines)



def document_registry_sha256(document: dict) -> str:
    import hashlib

    canonical = (json.dumps(document, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode()
    return hashlib.sha256(canonical).hexdigest()


def android_region(document: dict) -> str:
    android_metrics = [metric["android"] for metric in document["metrics"] if metric["android"]["status"] == "backed"]
    android_metrics.sort(key=lambda metric: metric["ordinal"])
    lines = [
        ANDROID_START,
        "// Generated by packages/healthmd-core-rust/scripts/generate-registry-adapters.py.",
        "// Persisted selection ids, order, categories, and units come from metric-registry-v1.json.",
        f"internal const val HEALTHMD_CORE_REGISTRY_SHA256 = {quoted(document_registry_sha256(document))}",
        "private val ALL_METRICS: List<HealthMetricDefinition> = listOf(",
    ]
    category_enum = {value: key for key, value in {
        "SLEEP": "Sleep", "ACTIVITY": "Activity", "HEART": "Heart", "RESPIRATORY": "Respiratory",
        "VITALS": "Vitals", "BODY": "Body", "NUTRITION": "Nutrition", "MOBILITY": "Mobility",
        "CYCLING": "Cycling", "HEARING": "Hearing", "MINDFULNESS": "Mindfulness",
        "REPRODUCTIVE": "Reproductive", "SYMPTOMS": "Symptoms", "MEDICATIONS": "Medications",
        "OTHER": "Other", "WORKOUTS": "Workouts",
    }.items()}
    for metric in android_metrics:
        lines.append(
            f"    HealthMetricDefinition({quoted(metric['selection_id'])}, "
            f"HealthMetricCategory.{category_enum[metric['category_id']]}, {quoted(metric['unit'])}),"
        )
    lines += [")", ANDROID_END]
    return "\n".join(lines)


def fields_region(document: dict) -> str:
    frozen = next(profile for profile in document["profiles"] if profile["id"] == "android_frozen_v4")
    outputs = frozen["outputs"]
    keys = [output["key"] for output in outputs]
    aliases = [output["key"] for output in outputs if output["alias_kind"] == "legacy_android"]
    native = [output["key"] for output in outputs if output["platform_native"]]
    lines = [
        FIELDS_START,
        "    // Generated from metric-registry-v1.json; exact order is contract metadata.",
        "    val allKeys: List<String> = listOf(",
        *[f"        {quoted(key)}," for key in keys],
        "    )",
        "",
        "    /** Duplicate pre-parity spellings/labels only. */",
        "    private val legacyAndroidAliasKeys: Set<String> = setOf(",
        *[f"        {quoted(key)}," for key in aliases],
        "    )",
        "",
        "    /** Android-native values with no exact frozen iOS-v4 equivalent. */",
        "    private val androidNativeFieldKeys: Set<String> = setOf(",
        *[f"        {quoted(key)}," for key in native],
        "    )",
        FIELDS_END,
    ]
    return "\n".join(lines)


def generated_ledger(document: dict) -> str:
    backed_android = [metric for metric in document["metrics"] if metric["android"]["status"] == "backed"]
    related: dict[str, list[str]] = {}
    non_equivalent: dict[str, list[str]] = {}
    for metric in backed_android:
        binding = metric["android"]
        if metric["equivalence"] == "platform_distinct":
            for semantic_id in binding.get("related_semantic_ids", []):
                non_equivalent.setdefault(semantic_id, []).append(binding["selection_id"])
            continue
        related.setdefault(metric["semantic_id"], []).append(binding["selection_id"])
        for semantic_id in binding.get("related_semantic_ids", []):
            related.setdefault(semantic_id, []).append(binding["selection_id"])
    apple_metrics = [metric for metric in document["metrics"] if metric["apple"]["status"] == "backed"]
    apple_metrics.sort(key=lambda metric: metric["apple"]["ordinal"])
    android_only = [metric for metric in backed_android if metric["apple"]["status"] == "unavailable"]
    android_only.sort(key=lambda metric: metric["android"]["ordinal"])
    lines = [
        "# Android ↔ Apple metric registry",
        "",
        "**Generated:** do not edit by hand. Source: `packages/healthmd-core-rust/crates/healthmd-core/registry/metric-registry-v1.json`.",
        "",
        "This inventory records an explicit Android decision for every current Apple metric. Hidden unavailable rows are contract accounting and are not fabricated as empty export fields.",
        "",
        "## iOS metric parity table",
        "",
        "| iOS metric id | iOS category | Android status | Android metric id(s) | Notes |",
        "|---|---|---|---|---|",
    ]
    for metric in apple_metrics:
        apple = metric["apple"]
        android_ids = related.get(metric["semantic_id"], [])
        if android_ids:
            status = "supported" if android_ids == [apple["selection_id"]] else "mapped/alias"
            notes = "Exact persisted id." if status == "supported" else "Explicit shared-registry mapping; native selectors remain platform-owned."
        else:
            status = "health-connect-unavailable"
            android_ids = [apple["selection_id"]]
            visibility = metric["android"].get("picker_visibility", "hidden")
            notes = f"Explicit unavailable decision ({visibility}); Android does not fabricate a parity value."
            if metric["semantic_id"] in non_equivalent:
                notes += " Related but non-equivalent Android selector(s): " + ", ".join(non_equivalent[metric["semantic_id"]]) + "."
        lines.append(
            f"| {apple['selection_id']} | {apple['category_id']} | {status} | {','.join(android_ids)} | {notes} |"
        )
    lines += [
        "",
        "## Android-only supported metrics",
        "",
        "| Android metric id | Android category | Unit | Android status | Notes |",
        "|---|---|---|---|---|",
    ]
    for metric in android_only:
        android = metric["android"]
        related_ids = android.get("related_semantic_ids", [])
        note = "Explicitly distinct platform semantic."
        if related_ids:
            note += " Related but non-equivalent to: " + ", ".join(related_ids) + "."
        lines.append(
            f"| {android['selection_id']} | {android['category_id'].upper().replace(' ', '_')} | {android['unit']} | android-only | {note} |"
        )
    lines += [
        "",
        "## Legacy unavailable aliases",
        "",
        "The registry preserves 102 unavailable/stale Android selection identities. Kotlin remains authoritative for their user-facing display/reason strings and shadow-checks every registry id, category, `label_key`, and `reason_key`; these identities remain non-toggleable.",
        "",
    ]
    return "\n".join(lines)


def website_page(document: dict) -> str:
    profiles = document["profiles"]
    apple_count = len(next(p for p in profiles if p["platform"] == "apple")["ordered_selection_ids"])
    android_count = len(next(p for p in profiles if p["platform"] == "android")["ordered_selection_ids"])
    semantic_count = len(document["metrics"])
    lines = [
        "---",
        "title: Shared metric registry",
        "description: Cross-platform Health.md metric identities and compatibility profiles.",
        "---",
        "",
        "<!-- Generated from packages/healthmd-core-rust/crates/healthmd-core/registry/metric-registry-v1.json. -->",
        "",
        "The shared Rust registry contains deterministic contract metadata while HealthKit and Health Connect capture, permissions, and availability checks remain native.",
        "",
        f"- {semantic_count} explicit semantic rows",
        f"- {apple_count} ordered Apple v7 selections",
        f"- {android_count} ordered Android selections",
        "- 102 preserved Android unavailable/stale identities",
        "- Three independent output profiles; no unified v8 schema",
        "",
        "| Internal profile | Public profile | Schema | Ordered selections | Output descriptors |",
        "|---|---|---:|---:|---:|",
    ]
    for profile in profiles:
        lines.append(
            f"| `{profile['id']}` | `{profile['public_profile_id']}` | {profile['public_schema_version']} | "
            f"{len(profile['ordered_selection_ids'])} | {len(profile['outputs'])} |"
        )
    lines += [
        "",
        "The [canonical registry JSON](/docs/reference/metric-registry-v1.json) is intended for contract inspection. Semantic IDs never replace persisted native selection IDs or public output keys.",
        "",
    ]
    return "\n".join(lines)


def update(path: Path, content: str, check: bool) -> bool:
    encoded = content.encode()
    if path.exists() and path.read_bytes() == encoded:
        return False
    if check:
        raise SystemExit(f"generated registry artifact is stale: {path.relative_to(REPO)}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded)
    print(f"updated {path.relative_to(REPO)}")
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = json.loads(REGISTRY.read_text())

    apple_text = APPLE.read_text()
    apple_text = replace_region(
        apple_text,
        APPLE_START,
        APPLE_END,
        apple_region(document),
        "// MARK: - All Health Metrics",
        "// MARK: - Metric Selection State",
    )
    mapping_text = APPLE_MAPPING.read_text()
    mapping_text = replace_region(
        mapping_text,
        APPLE_MAPPING_START,
        APPLE_MAPPING_END,
        apple_mapping_region(document),
        "    /// Reviewed metrics whose public output",
        "    static let allKnownFrontmatterKeys:",
    )
    android_text = ANDROID.read_text()
    android_text = replace_region(
        android_text,
        ANDROID_START,
        ANDROID_END,
        android_region(document),
        "private val ALL_METRICS:",
        "private val UNAVAILABLE_METRICS:",
    )
    fields_text = ANDROID_FIELDS.read_text()
    fields_text = replace_region(
        fields_text,
        FIELDS_START,
        FIELDS_END,
        fields_region(document),
        "    val allKeys:",
        "    /**\n     * Extracts all health fields",
    )

    update(APPLE, apple_text, args.check)
    update(APPLE_MAPPING, mapping_text, args.check)
    update(ANDROID, android_text, args.check)
    update(ANDROID_FIELDS, fields_text, args.check)
    update(LEDGER, generated_ledger(document), args.check)
    update(WEBSITE_PAGE, website_page(document), args.check)
    update(WEBSITE_JSON, REGISTRY.read_text(), args.check)
    if args.check:
        print("Generated native registry adapters and public references are current")


if __name__ == "__main__":
    main()
