package com.healthmd.direct

import android.content.Context
import android.os.Build
import android.os.Process
import android.os.UserManager
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.system.Os
import com.healthmd.direct.protocol.AgentBridgeCodec
import com.healthmd.direct.protocol.AgentBridgeErrorCode
import com.healthmd.direct.protocol.AgentBridgeException
import java.nio.ByteBuffer
import java.nio.channels.FileChannel
import java.nio.file.Files
import java.nio.file.LinkOption.NOFOLLOW_LINKS
import java.nio.file.NoSuchFileException
import java.nio.file.Path
import java.nio.file.StandardOpenOption.READ
import java.nio.file.attribute.GroupPrincipal
import java.nio.file.attribute.PosixFileAttributes
import java.nio.file.attribute.UserPrincipal
import java.security.KeyStore
import java.security.MessageDigest
import java.time.Instant
import java.util.Base64
import java.util.UUID
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

/** Load ONLY the existing native Direct CLI pairing record. Never construct its mutating store.
 * Pairing is not an authenticated channel, negotiated session, foreground service, delegation,
 * exact consent, health/configuration/destination permission or entitlement. No bridge wiring.
 * No cache, creating getter, key generation, prompt, repair, fallback, renewal or migration.
 * File/key checks sample observable boundaries; NOT persisted fresh-open protection, anti-rollback,
 * a global filesystem/key/session transaction or recall of already-read material. */
internal class AgentBridgeExportNativeTrust(private val context: Context) {
    /** Non-wire immutable snapshot; only the private implementation is accepted for current checks.
     * Unlike the legacy data classes, neither autogenerated toString nor serialization exposes it. */
    sealed interface Snapshot {
        val sourceInstallationId: String
        val hostInstallationId: String
        val displayName: String
        val host: String
        val port: Int
        val pairedAt: Instant
        fun copyReconnectSecret(): ByteArray
    }

    /** Clean absence (directory/unpaired trust/key) is null. Present unsafe/corrupt/partial state
     * is binding_changed; inaccessible native protection/key/metadata is permission_required.
     * In particular a present trust file with no valid original source identity never invents one. */
    fun loadExisting(): Snapshot? = safe {
        val users = available()
        val (uid, gid) = nativeIds()
        val data = dataPath()
        val parent = data.resolve("no_backup")
        val root = parent.resolve("direct-cli")
        val directories = listOf(data, parent, root).associateWith { path ->
            observeOrNull(path, true, uid, gid, sdkOwned = path != root) ?: return@safe null
        }
        val identity = root.resolve("installation-id")
        val trust = root.resolve("trust.enc")
        val trustObservation = observeOrNull(trust, false, uid, gid) ?: return@safe null
        val identityObservation = observeOrNull(identity, false, uid, gid) ?: fail()
        demand(identityObservation.size == 36L)
        demand(trustObservation.size in 29..MAX_BYTES.toLong()) // nonce12 + tag16 + nonempty JSON.
        val identityBytes = read(identity, identityObservation, uid, gid, 36)
        val sourceId = identityBytes.toString(Charsets.US_ASCII)
        demand(canonicalId(sourceId))
        val encrypted = read(trust, trustObservation, uid, gid, MAX_BYTES)
        val key = existingKey() ?: return@safe null
        val plaintext = decrypt(key, encrypted)
        try {
            // Generic strict parser only: preserves legacy names, rejects decoded duplicates,
            // bad UTF8/scalars and noninteger port BEFORE the closed legacy serialization decode.
            val canonical = try { AgentBridgeCodec.canonicalize(plaintext) } catch (_: Exception) { fail() }
            val stored = json.decodeFromString<StoredTrust>(canonical.decodeToString())
            demand(canonical.contentEquals(AgentBridgeCodec.canonicalize(json.encodeToString(stored).toByteArray())))
            demand(canonicalId(stored.installationId))
            demand(boundedText(stored.displayName) && boundedText(stored.host) && stored.host == stored.host.trim())
            demand(stored.port in 1..65535 && stored.pairedAt.length in 1..64)
            val pairedAt = Instant.parse(stored.pairedAt)
            demand(Regex("[A-Za-z0-9+/]{43}=").matches(stored.reconnectSecretBase64))
            val secret = Base64.getDecoder().decode(stored.reconnectSecretBase64)
            try {
                demand(secret.size == 32 && Base64.getEncoder().encodeToString(secret) == stored.reconnectSecretBase64)
                val observations = directories + mapOf(identity to identityObservation, trust to trustObservation)
                // Re-read native provenance/key availability and actual original files after SDK/crypto.
                val currentKey = existingKey() ?: fail()
                demand(currentKey == key)
                // Descriptor/alias equality alone cannot identify a native key generation. Also
                // confirm the current native handle still decrypts these ORIGINAL encrypted bytes.
                val currentPlaintext = decrypt(currentKey, encrypted)
                try { demand(MessageDigest.isEqual(digest(currentPlaintext), digest(plaintext))) }
                finally { currentPlaintext.fill(0) }
                available()
                demand(users.isUserUnlocked, AgentBridgeErrorCode.PERMISSION_REQUIRED)
                demand(dataPath() == data && nativeIds() == (uid to gid))
                directories.forEach { (path, before) -> demand(observe(path, true, uid, gid, path != root) == before) }
                demand(read(identity, identityObservation, uid, gid, 36).contentEquals(identityBytes))
                demand(read(trust, trustObservation, uid, gid, MAX_BYTES).contentEquals(encrypted))
                Loaded(sourceId, stored.installationId, stored.displayName, stored.host, stored.port, pairedAt,
                    secret, key, observations, digest(encrypted), digest(plaintext))
            } finally { secret.fill(0) }
        } finally { plaintext.fill(0) }
    }

    /** Match ORIGINAL native material to identities/credential established elsewhere by a native
     * authenticated connection. This comparison does not itself establish that connection/rights.
     * Re-read every time; never silently switch to same-ID replacement trust or a new endpoint. */
    fun requireCurrent(original: Snapshot, authenticatedSourceInstallationId: String,
        authenticatedHostInstallationId: String, originalReconnectSecret: ByteArray) = safe {
        demand(originalReconnectSecret.size == 32)
        val expected = originalReconnectSecret.copyOf()
        try {
            val before = original as? Loaded ?: fail()
            demand(before.sourceInstallationId == authenticatedSourceInstallationId &&
                before.hostInstallationId == authenticatedHostInstallationId && before.secretEquals(expected))
            val current = loadExisting() as? Loaded ?: fail()
            demand(current.sourceInstallationId == before.sourceInstallationId &&
                current.hostInstallationId == before.hostInstallationId && current.displayName == before.displayName &&
                current.host == before.host && current.port == before.port && current.pairedAt == before.pairedAt &&
                current.key == before.key && current.secretEquals(expected) && current.observations == before.observations &&
                MessageDigest.isEqual(current.encryptedDigest, before.encryptedDigest) &&
                MessageDigest.isEqual(current.recordDigest, before.recordDigest))
            // Native key-handle equality is NOT a unique key-generation witness. These raw-byte
            // and original inode fences reject observable replacement, not privileged valid-snapshot
            // rollback or restoration on fresh open. A new authenticated context is separate work.
        } finally { expected.fill(0) }
    }

    private class Loaded(override val sourceInstallationId: String, override val hostInstallationId: String,
        override val displayName: String, override val host: String, override val port: Int,
        override val pairedAt: Instant, secret: ByteArray, val key: SecretKey,
        val observations: Map<Path, Observation>, encryptedDigest: ByteArray, recordDigest: ByteArray) : Snapshot {
        private val reconnectSecret = secret.copyOf()
        val encryptedDigest = encryptedDigest.copyOf()
        val recordDigest = recordDigest.copyOf() // RAW legacy plaintext, never canonical serialization.
        override fun copyReconnectSecret() = reconnectSecret.copyOf()
        fun secretEquals(value: ByteArray) = value.size == 32 && MessageDigest.isEqual(reconnectSecret, value)
        override fun toString() = "AgentBridgeExportNativeTrust.Snapshot(redacted)"
    }

    private fun available(): UserManager = try {
        demand(!context.isDeviceProtectedStorage, AgentBridgeErrorCode.PERMISSION_REQUIRED)
        val users = context.getSystemService(UserManager::class.java) ?: fail(AgentBridgeErrorCode.PERMISSION_REQUIRED)
        demand(users.isUserUnlocked, AgentBridgeErrorCode.PERMISSION_REQUIRED) // BFU, NOT Keyguard/screen lock.
        users
    } catch (_: Exception) { fail(AgentBridgeErrorCode.PERMISSION_REQUIRED) }
    private fun nativeIds(): Pair<Int, Int> = try { Process.myUid() to Os.getgid() }
        catch (_: Exception) { fail(AgentBridgeErrorCode.PERMISSION_REQUIRED) }
    private fun dataPath(): Path {
        val path = context.dataDir.toPath()
        demand(path.isAbsolute && path == path.toAbsolutePath().normalize())
        return path
    }
    private fun existingKey(): SecretKey? = try {
        val store = KeyStore.getInstance(KEYSTORE)
        demand(store.provider.name == KEYSTORE, AgentBridgeErrorCode.PERMISSION_REQUIRED)
        store.load(null)
        val raw = store.getKey(PAIRING_ALIAS, null)
        if (raw == null) null else {
            val key = raw as? SecretKey ?: fail(AgentBridgeErrorCode.PERMISSION_REQUIRED)
            demand(key.algorithm == KeyProperties.KEY_ALGORITHM_AES, AgentBridgeErrorCode.PERMISSION_REQUIRED)
            val factory = SecretKeyFactory.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
            demand(factory.provider.name == KEYSTORE, AgentBridgeErrorCode.PERMISSION_REQUIRED)
            val info = factory.getKeySpec(key, KeyInfo::class.java) as? KeyInfo ?: fail(AgentBridgeErrorCode.PERMISSION_REQUIRED)
            // Native factory establishes provenance; SDK-owned software-backed keys are valid too.
            demand(info.keystoreAlias == PAIRING_ALIAS && info.origin == KeyProperties.ORIGIN_GENERATED &&
                info.keySize == 256 && info.purposes == (KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT) &&
                info.blockModes.contentEquals(arrayOf(KeyProperties.BLOCK_MODE_GCM)) &&
                info.encryptionPaddings.contentEquals(arrayOf(KeyProperties.ENCRYPTION_PADDING_NONE)) &&
                !info.isTrustedUserPresenceRequired && !info.isUserConfirmationRequired, AgentBridgeErrorCode.PERMISSION_REQUIRED)
            // Reject limited/exhausted keys BEFORE any cipher operation can consume a use.
            // API28-30 must never invoke this API31 metadata; ordinary later lock is not BFU.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) demand(
                info.remainingUsageCount == KeyProperties.UNRESTRICTED_USAGE_COUNT, AgentBridgeErrorCode.PERMISSION_REQUIRED)
            key // Native handle only; never call encoded/getEncoded or use a JVM/plaintext fallback.
        }
    } catch (_: Exception) { fail(AgentBridgeErrorCode.PERMISSION_REQUIRED) }

    private fun decrypt(key: SecretKey, encrypted: ByteArray): ByteArray {
        val cipher = try {
            Cipher.getInstance(CIPHER).apply {
                init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(128, encrypted.copyOfRange(0, 12)))
            }
        } catch (_: Exception) { fail(AgentBridgeErrorCode.PERMISSION_REQUIRED) }
        return try { cipher.doFinal(encrypted, 12, encrypted.size - 12) }
        catch (_: AEADBadTagException) { fail() }
        catch (_: Exception) { fail(AgentBridgeErrorCode.PERMISSION_REQUIRED) }
    }

    private data class Observation(val identity: Any, val owner: UserPrincipal, val group: GroupPrincipal,
        val mode: Int, val size: Long, val modified: Any?)
    private fun observeOrNull(path: Path, directory: Boolean, uid: Int, gid: Int, sdkOwned: Boolean = false): Observation? =
        try { observe(path, directory, uid, gid, sdkOwned) } catch (_: NoSuchFileException) { null }
    private fun observe(path: Path, directory: Boolean, uid: Int, gid: Int, sdkOwned: Boolean = false): Observation {
        val attrs = Files.readAttributes(path, PosixFileAttributes::class.java, NOFOLLOW_LINKS)
        demand(!attrs.isSymbolicLink && (if (directory) attrs.isDirectory else attrs.isRegularFile) && attrs.fileKey() != null)
        demand(path.toRealPath() == path)
        demand((Files.getAttribute(path, "unix:uid", NOFOLLOW_LINKS) as Number).toInt() == uid &&
            (Files.getAttribute(path, "unix:gid", NOFOLLOW_LINKS) as Number).toInt() == gid)
        val mode = (Files.getAttribute(path, "unix:mode", NOFOLLOW_LINKS) as Number).toInt() and 0xfff
        // The0771 exception belongs ONLY to exact Context-derived SDK data/no_backup parents.
        // Leaf/files remain private0700/0600, including special-bit rejection; never chmod/repair.
        demand(if (directory) mode == 448 || (sdkOwned && mode == 505) else mode == 384)
        if (!directory) demand((Files.getAttribute(path, "unix:nlink", NOFOLLOW_LINKS) as Number).toLong() == 1L)
        return Observation(requireNotNull(attrs.fileKey()), attrs.owner(), attrs.group(), mode,
            if (directory) 0 else attrs.size(), if (directory) null else attrs.lastModifiedTime())
    }
    private fun read(path: Path, before: Observation, uid: Int, gid: Int, maximum: Int): ByteArray {
        demand(before.size in 1..maximum.toLong())
        demand(observe(path, false, uid, gid) == before)
        val bytes = FileChannel.open(path, READ, NOFOLLOW_LINKS).use { channel ->
            demand(channel.size() == before.size)
            val buffer = ByteBuffer.allocate(before.size.toInt())
            while (buffer.hasRemaining()) demand(channel.read(buffer) > 0)
            demand(channel.size() == before.size)
            buffer.array()
        }
        demand(observe(path, false, uid, gid) == before)
        return bytes
    }

    // ACTUAL DirectCliTrustStore writer grammar, not an agent delegation/grant schema.
    // Private non-data class avoids autogenerated secret-bearing toString even on decoder records.
    @Serializable
    private class StoredTrust(val installationId: String, val displayName: String,
        val reconnectSecretBase64: String, val host: String, val port: Int, val pairedAt: String)

    private companion object {
        const val KEYSTORE = "AndroidKeyStore"
        const val PAIRING_ALIAS = "healthmd-direct-cli-trust-v1" // AES pairing ONLY, never issuer HMAC/consent.
        const val CIPHER = "AES/GCM/NoPadding"
        const val MAX_BYTES = 65536
        val json = Json { encodeDefaults = true; ignoreUnknownKeys = false; isLenient = false; coerceInputValues = false }
        fun digest(bytes: ByteArray) = MessageDigest.getInstance("SHA-256").digest(bytes)
        fun canonicalId(value: String) = value.length == 36 && UUID.fromString(value).toString() == value
        fun boundedText(value: String) = value.isNotBlank() && value.codePointCount(0, value.length) <= 4096
        fun demand(value: Boolean, code: AgentBridgeErrorCode = AgentBridgeErrorCode.BINDING_CHANGED) { if (!value) fail(code) }
        fun fail(code: AgentBridgeErrorCode = AgentBridgeErrorCode.BINDING_CHANGED): Nothing = throw AgentBridgeException(code)
        inline fun <T> safe(block: () -> T): T = try { block() } catch (e: AgentBridgeException) { throw e }
            catch (_: Exception) { fail() } // No rejected values/parser/native exception retained in errors.
    }
}
