// Generated by packages/contracts/diagnostics/generate.py; do not edit.
import Foundation

nonisolated enum DiagnosticEventID: String, Codable, CaseIterable, Sendable {
    case appStarted = "app.started"
    case nativeLifecycle = "app.native_lifecycle"
    case advertisingStarted = "sync.advertising_started"
    case advertisingStopped = "sync.advertising_stopped"
    case browsingStarted = "sync.browsing_started"
    case browsingStopped = "sync.browsing_stopped"
    case peerDiscovered = "sync.peer_discovered"
    case peerLost = "sync.peer_lost"
    case invitationSent = "sync.invitation_sent"
    case invitationReceived = "sync.invitation_received"
    case invitationTimeout = "sync.invitation_timeout"
    case connectionChanged = "sync.connection_changed"
    case capabilitiesReceived = "sync.capabilities_received"
    case destinationChanged = "sync.destination_changed"
    case messageSent = "sync.message_sent"
    case messageReceived = "sync.message_received"
    case transportError = "sync.transport_error"
    case exportResult = "export.result"
    case requestQueued = "schedule.request_queued"
    case attemptStarted = "schedule.attempt_started"
    case attemptFinished = "schedule.attempt_finished"
    case backgroundExpired = "schedule.background_expired"
    case triggerReceived = "schedule.trigger_received"
    case workerResult = "schedule.worker_result"
    case notificationRequested = "notification.requested"
    case notificationCancelled = "notification.cancelled"
    case notificationTapped = "notification.tapped"
    case notificationFailed = "notification.request_failed"
    case recordingStarted = "diagnostics.recording_started"
    case recordingStopped = "diagnostics.recording_stopped"

    var subsystem: String {
        switch self {
        case .appStarted: return "lifecycle"
        case .nativeLifecycle: return "lifecycle"
        case .advertisingStarted: return "connection"
        case .advertisingStopped: return "connection"
        case .browsingStarted: return "connection"
        case .browsingStopped: return "connection"
        case .peerDiscovered: return "connection"
        case .peerLost: return "connection"
        case .invitationSent: return "connection"
        case .invitationReceived: return "connection"
        case .invitationTimeout: return "connection"
        case .connectionChanged: return "connection"
        case .capabilitiesReceived: return "connection"
        case .destinationChanged: return "connection"
        case .messageSent: return "connection"
        case .messageReceived: return "connection"
        case .transportError: return "connection"
        case .exportResult: return "export"
        case .requestQueued: return "schedule"
        case .attemptStarted: return "schedule"
        case .attemptFinished: return "schedule"
        case .backgroundExpired: return "schedule"
        case .triggerReceived: return "schedule"
        case .workerResult: return "schedule"
        case .notificationRequested: return "notification"
        case .notificationCancelled: return "notification"
        case .notificationTapped: return "notification"
        case .notificationFailed: return "notification"
        case .recordingStarted: return "diagnostics"
        case .recordingStopped: return "diagnostics"
        }
    }

    var severity: String {
        switch self {
        case .appStarted: return "info"
        case .nativeLifecycle: return "info"
        case .advertisingStarted: return "debug"
        case .advertisingStopped: return "debug"
        case .browsingStarted: return "debug"
        case .browsingStopped: return "debug"
        case .peerDiscovered: return "debug"
        case .peerLost: return "debug"
        case .invitationSent: return "debug"
        case .invitationReceived: return "debug"
        case .invitationTimeout: return "warning"
        case .connectionChanged: return "info"
        case .capabilitiesReceived: return "debug"
        case .destinationChanged: return "debug"
        case .messageSent: return "trace"
        case .messageReceived: return "trace"
        case .transportError: return "error"
        case .exportResult: return "info"
        case .requestQueued: return "info"
        case .attemptStarted: return "info"
        case .attemptFinished: return "info"
        case .backgroundExpired: return "warning"
        case .triggerReceived: return "debug"
        case .workerResult: return "info"
        case .notificationRequested: return "info"
        case .notificationCancelled: return "debug"
        case .notificationTapped: return "info"
        case .notificationFailed: return "error"
        case .recordingStarted: return "info"
        case .recordingStopped: return "info"
        }
    }
}

nonisolated enum DiagnosticField: String, Codable, CaseIterable, Sendable {
    case nativeCallback = "native_callback"
    case state = "state"
    case transport = "transport"
    case trigger = "trigger"
    case reason = "reason"
    case errorDomain = "error_domain"
    case errorCode = "error_code"
    case durationMs = "duration_ms"
    case byteCount = "byte_count"
    case fileCount = "file_count"
    case dayCount = "day_count"
    case ready = "ready"
    case pendingOnly = "pending_only"
    case operationId = "operation_id"
    case peerAlias = "peer_alias"
    case peerName = "peer_name"

    var isPrivate: Bool {
        switch self {
        case .nativeCallback: return false
        case .state: return false
        case .transport: return false
        case .trigger: return false
        case .reason: return false
        case .errorDomain: return false
        case .errorCode: return false
        case .durationMs: return false
        case .byteCount: return false
        case .fileCount: return false
        case .dayCount: return false
        case .ready: return false
        case .pendingOnly: return false
        case .operationId: return false
        case .peerAlias: return false
        case .peerName: return true
        }
    }

    func accepts(_ value: DiagnosticValue) -> Bool {
        switch (self, value) {
        case (.nativeCallback, .text(let text)): return ["ios_application_did_become_active", "ios_scene_phase_active", "ios_scene_phase_inactive", "ios_scene_phase_background", "macos_application_did_become_active", "macos_application_did_resign_active", "android_activity_resumed", "android_activity_paused"].contains(text)
        case (.state, .text(let text)): return ["disconnected", "connecting", "connected", "pairing", "transferring", "completed", "failed", "unknown"].contains(text)
        case (.transport, .text(let text)): return ["nearby", "manual_ip"].contains(text)
        case (.trigger, .text(let text)): return ["app_open", "silent_push", "background_task", "notification", "handshake", "schedule", "manual"].contains(text)
        case (.reason, .text(let text)): return ["success", "partial", "failure", "cancelled", "timeout", "suspended", "retry", "unknown"].contains(text)
        case (.errorDomain, .text(let text)): return ["NSPOSIXErrorDomain", "NSCocoaErrorDomain", "NSURLErrorDomain", "MCErrorDomain", "HKErrorDomain", "IOException", "SecurityException", "unknown"].contains(text)
        case (.errorCode, .integer(let number)): return number >= -9_007_199_254_740_991 && number <= 9_007_199_254_740_991
        case (.durationMs, .integer(let number)): return number >= 0 && number <= 9_007_199_254_740_991
        case (.byteCount, .integer(let number)): return number >= 0 && number <= 9_007_199_254_740_991
        case (.fileCount, .integer(let number)): return number >= 0 && number <= 9_007_199_254_740_991
        case (.dayCount, .integer(let number)): return number >= 0 && number <= 9_007_199_254_740_991
        case (.ready, .boolean): return true
        case (.pendingOnly, .boolean): return true
        case (.operationId, .text(let text)): return UUID(uuidString: text) != nil && text.count == 36
        case (.peerAlias, .text(let text)): return text.range(of: "^peer_[0-9]{1,3}$", options: .regularExpression) != nil
        case (.peerName, .text(let text)): return text.utf8.count <= 512
        default: return false
        }
    }
}
