//
//  SnapshotHelper.swift
//  Generated by fastlane
//
//  This file will be automatically updated by fastlane when running snapshot
//  To customize, create a copy and modify as needed
//

import Foundation
import XCTest

var deviceLanguage = ""
var locale = ""

func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
    Snapshot.setupSnapshot(app, waitForAnimations: waitForAnimations)
}

func snapshot(_ name: String, waitForLoadingIndicator: Bool) {
    Snapshot.snapshot(name, waitForLoadingIndicator: waitForLoadingIndicator)
}

func snapshot(_ name: String) {
    Snapshot.snapshot(name)
}

enum SnapshotError: Error, CustomDebugStringConvertible {
    case cannotDetectUser
    case cannotFindHomeDirectory
    case cannotFindSimulatorHomeDirectory
    case cannotAccessSimulatorHomeDirectory(String)
    case cannotRunOnPhysicalDevice

    var debugDescription: String {
        switch self {
        case .cannotDetectUser:
            return "Couldn't find Snapshot configuration files - can't detect current user"
        case .cannotFindHomeDirectory:
            return "Couldn't find Snapshot configuration files - can't detect `NSHomeDirectory`"
        case .cannotFindSimulatorHomeDirectory:
            return "Couldn't find simulator home location."
        case .cannotAccessSimulatorHomeDirectory(let simulatorPath):
            return "Can't prepare environment. Simulator home location is not accessible: \(simulatorPath)"
        case .cannotRunOnPhysicalDevice:
            return "Can't use Snapshot on a physical device."
        }
    }
}

@objcMembers
open class Snapshot: NSObject {
    static var app: XCUIApplication?
    static var waitForAnimations = true

    open class func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
        Snapshot.app = app
        Snapshot.waitForAnimations = waitForAnimations
    }

    open class func snapshot(_ name: String, waitForLoadingIndicator: Bool = false) {
        if waitForLoadingIndicator {
            waitForLoadingIndicatorToDisappear()
        }

        print("snapshot: \(name)")

        if Snapshot.waitForAnimations {
            sleep(1)
        }

        #if os(iOS)
        guard let app = self.app else {
            print("XCUIApplication is not set. Please call setupSnapshot(app) before taking a snapshot.")
            return
        }

        let screenshot = app.windows.firstMatch.screenshot()
        let attachment = XCTAttachment(screenshot: screenshot)
        attachment.name = name
        attachment.lifetime = .keepAlways
        XCTContext.runActivity(named: "Screenshot: \(name)") { _ in
            add(attachment)
        }
        #endif
    }

    class func waitForLoadingIndicatorToDisappear() {
        let query = XCUIApplication().statusBars.children(matching: .other).element(boundBy: 1).children(matching: .other)

        while query.count > 4 {
            sleep(1)
            print("Number of elements in status bar: \(query.count)... waiting for it to be 4 or less")
        }
    }
}

// Please don't remove the lines below
// They are used to detect outdated configuration files
// SnapshotHelperVersion [1.32]
