package com.healthmd.sharedsetup

/**
 * Cross-platform alias evidence generated from the canonical metric-registry-v1.json.
 * Selection IDs are translation evidence only; semantic IDs remain application authority.
 */
internal data class CanonicalSharedSetupAlias(
    val semanticId: String,
    val appleSelectionId: String?,
    val androidSelectionId: String,
    val equivalence: String,
)

internal val ANDROID_SHARED_SETUP_ALIASES: Map<String, CanonicalSharedSetupAlias> = listOf(
    CanonicalSharedSetupAlias("sleep_total", "sleep_total", "sleep_total", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("sleep_deep", "sleep_deep", "sleep_deep", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("sleep_rem", "sleep_rem", "sleep_rem", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("sleep_core", "sleep_core", "sleep_light", "mapped_alias"),
    CanonicalSharedSetupAlias("sleep_awake", "sleep_awake", "sleep_awake", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("sleep_in_bed", "sleep_in_bed", "sleep_in_bed", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("steps", "steps", "steps", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("distance_walking_running", "distance_walking_running", "distance", "mapped_alias"),
    CanonicalSharedSetupAlias("distance_swimming", "distance_swimming", "swimming_distance", "mapped_alias"),
    CanonicalSharedSetupAlias("distance_wheelchair", "distance_wheelchair", "wheelchair_distance", "mapped_alias"),
    CanonicalSharedSetupAlias("distance_downhill_snow", "distance_downhill_snow", "downhill_snow_distance", "mapped_alias"),
    CanonicalSharedSetupAlias("active_energy", "active_energy", "active_calories", "mapped_alias"),
    CanonicalSharedSetupAlias("basal_energy", "basal_energy", "basal_calories", "mapped_alias"),
    CanonicalSharedSetupAlias("exercise_time", "exercise_time", "exercise_minutes", "mapped_alias"),
    CanonicalSharedSetupAlias("flights_climbed", "flights_climbed", "flights_climbed", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("swimming_strokes", "swimming_strokes", "swimming_strokes", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("push_count", "push_count", "wheelchair_pushes", "mapped_alias"),
    CanonicalSharedSetupAlias("vo2_max", "vo2_max", "vo2_max", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("heart_rate_avg", "heart_rate_avg", "avg_hr", "mapped_alias"),
    CanonicalSharedSetupAlias("heart_rate_min", "heart_rate_min", "min_hr", "mapped_alias"),
    CanonicalSharedSetupAlias("heart_rate_max", "heart_rate_max", "max_hr", "mapped_alias"),
    CanonicalSharedSetupAlias("resting_heart_rate", "resting_heart_rate", "resting_hr", "mapped_alias"),
    CanonicalSharedSetupAlias("walking_heart_rate", "walking_heart_rate", "walking_hr", "mapped_alias"),
    CanonicalSharedSetupAlias("respiratory_rate", "respiratory_rate", "respiratory_rate", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("blood_oxygen", "blood_oxygen", "blood_oxygen", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("body_temperature", "body_temperature", "body_temp", "mapped_alias"),
    CanonicalSharedSetupAlias("basal_body_temperature", "basal_body_temperature", "basal_body_temp", "mapped_alias"),
    CanonicalSharedSetupAlias("blood_pressure_systolic", "blood_pressure_systolic", "bp_systolic", "mapped_alias"),
    CanonicalSharedSetupAlias("blood_pressure_diastolic", "blood_pressure_diastolic", "bp_diastolic", "mapped_alias"),
    CanonicalSharedSetupAlias("blood_glucose", "blood_glucose", "blood_glucose", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("weight", "weight", "weight", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("height", "height", "height", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("bmi", "bmi", "bmi", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("body_fat", "body_fat", "body_fat", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("lean_body_mass", "lean_body_mass", "lean_mass", "mapped_alias"),
    CanonicalSharedSetupAlias("walking_speed", "walking_speed", "walking_speed", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("running_speed", "running_speed", "running_speed", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("running_power", "running_power", "running_power", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("cycling_distance", "cycling_distance", "cycling_distance", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("cycling_power", "cycling_power", "power_avg", "mapped_alias"),
    CanonicalSharedSetupAlias("cycling_cadence", "cycling_cadence", "cycling_cadence", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("dietary_energy", "dietary_energy", "dietary_energy", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("dietary_protein", "dietary_protein", "protein", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_carbs", "dietary_carbs", "carbs", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_fat", "dietary_fat", "fat", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_fat_saturated", "dietary_fat_saturated", "saturated_fat", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_fat_mono", "dietary_fat_mono", "monounsaturated_fat", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_fat_poly", "dietary_fat_poly", "polyunsaturated_fat", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_cholesterol", "dietary_cholesterol", "cholesterol", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_fiber", "dietary_fiber", "fiber", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_sugar", "dietary_sugar", "sugar", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_sodium", "dietary_sodium", "sodium", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_water", "dietary_water", "water", "mapped_alias"),
    CanonicalSharedSetupAlias("dietary_caffeine", "dietary_caffeine", "caffeine", "mapped_alias"),
    CanonicalSharedSetupAlias("vitamin_a", "vitamin_a", "vitamin_a", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("vitamin_b6", "vitamin_b6", "vitamin_b6", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("vitamin_b12", "vitamin_b12", "vitamin_b12", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("vitamin_c", "vitamin_c", "vitamin_c", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("vitamin_d", "vitamin_d", "vitamin_d", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("vitamin_e", "vitamin_e", "vitamin_e", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("vitamin_k", "vitamin_k", "vitamin_k", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("thiamin", "thiamin", "thiamin", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("riboflavin", "riboflavin", "riboflavin", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("niacin", "niacin", "niacin", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("folate", "folate", "folate", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("biotin", "biotin", "biotin", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("pantothenic_acid", "pantothenic_acid", "pantothenic_acid", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("calcium", "calcium", "calcium", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("iron", "iron", "iron", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("potassium", "potassium", "potassium", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("magnesium", "magnesium", "magnesium", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("phosphorus", "phosphorus", "phosphorus", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("zinc", "zinc", "zinc", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("selenium", "selenium", "selenium", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("copper", "copper", "copper", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("manganese", "manganese", "manganese", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("chromium", "chromium", "chromium", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("molybdenum", "molybdenum", "molybdenum", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("chloride", "chloride", "chloride", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("iodine", "iodine", "iodine", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("mindful_minutes", "mindful_minutes", "mindful_minutes", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("mindful_sessions", "mindful_sessions", "mindful_sessions", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("menstrual_flow", "menstrual_flow", "menstrual_flow", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("sexual_activity", "sexual_activity", "sexual_activity", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("ovulation_test", "ovulation_test", "ovulation_test", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("cervical_mucus", "cervical_mucus", "cervical_mucus", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("intermenstrual_bleeding", "intermenstrual_bleeding", "intermenstrual_bleeding", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("workouts", "workouts", "workouts", "platform_exact_or_unavailable"),
    CanonicalSharedSetupAlias("android.total_calories", null, "total_calories", "platform_distinct"),
    CanonicalSharedSetupAlias("android.elevation_gained", null, "elevation_gained", "platform_distinct"),
    CanonicalSharedSetupAlias("android.activity_intensity_minutes", null, "activity_intensity_minutes", "platform_distinct"),
    CanonicalSharedSetupAlias("android.hrv_rmssd", null, "hrv", "platform_distinct"),
    CanonicalSharedSetupAlias("android.skin_temperature", null, "skin_temperature", "platform_distinct"),
    CanonicalSharedSetupAlias("android.body_water_mass", null, "body_water_mass", "platform_distinct"),
    CanonicalSharedSetupAlias("android.bone_mass", null, "bone_mass", "platform_distinct"),
    CanonicalSharedSetupAlias("android.unsaturated_fat", null, "unsaturated_fat", "platform_distinct"),
    CanonicalSharedSetupAlias("android.trans_fat", null, "trans_fat", "platform_distinct"),
    CanonicalSharedSetupAlias("android.folic_acid", null, "folic_acid", "platform_distinct"),
    CanonicalSharedSetupAlias("android.energy_from_fat", null, "energy_from_fat", "platform_distinct"),
    CanonicalSharedSetupAlias("android.nutrition_meals", null, "nutrition_meals", "platform_distinct"),
    CanonicalSharedSetupAlias("android.steps_cadence", null, "steps_cadence", "platform_distinct"),
    CanonicalSharedSetupAlias("android.power_max", null, "power_max", "platform_distinct"),
    CanonicalSharedSetupAlias("android.menstruation_periods", null, "menstruation_periods", "platform_distinct"),
    CanonicalSharedSetupAlias("android.menstruation_period_days", null, "menstruation_period_days", "platform_distinct"),
    CanonicalSharedSetupAlias("android.planned_workouts", null, "planned_workouts", "platform_distinct"),
    CanonicalSharedSetupAlias("android.medical_resources", null, "medical_resources", "platform_distinct"),
).associateBy { it.semanticId }
